### ISSUE TITLE
[Docs]: next-pwa preloading defaults may not be optimal for avg user

### ISSUE THREAD

**Issue by Enalmada** [DuCanhGH/next-pwa#101]
### Provide environment information

next 13.5.3
@ducanh2912/next-pwa 9.7.1

### Whose documentation is this feedback for?

[Configuring](https://ducanh-next-pwa.vercel.app/docs/next-pwa/configuring)

### Describe the problem

First off, thanks @DuCanhGH for your work to keep the next-pwa concept alive.  You are a reminder and inspiration that one person can make a big community difference and that we all must help out how we can.  In that spirit, when I was testing out next-pwa I saw some things that I think you and others might not actually want happening and might need some discussion, consideration, documentation, or default changes.      

#### source maps
I noticed my server was preloading .map files even though Next.js says they are [opt in](https://nextjs.org/docs/app/api-reference/next-config-js/productionBrowserSourceMaps) and I do not have them turned on but I do use sentry and I now notice that [it turns them on](https://github.com/vercel/next.js/discussions/32920).  I don't believe the pwa should ever preload these even if they exist.  I believe the default should exclude these:
```
buildExcludes: [ /\.map$/ ]  // Exclude all .map files
```

#### font files
next-pwa is configured with a [maxEntries of 4](https://github.com/DuCanhGH/next-pwa/blob/master/packages/next-pwa/src/cache.ts#L33).   

Next.js [font loading](https://nextjs.org/docs/pages/building-your-application/optimizing/fonts#google-fonts) has all subsets in the build.  I have only used Inter but I assume most fonts have more than 4 subsets which means a most important subset (like latin for me personally) might be pushed out of cache depending on order.  One option would be to increase preloading beyond 4 but I think fonts are big and we don't want to download unused subsets.  next/font `const inter = Inter({ subsets: ['latin'] })`  seems to put a `.p` (prioritized?) on the files you call out in the subsets list.  I believe the default should be:
```
buildExcludes: [ /(?<!\.p)\.woff2$/ ]  // Exclude all .woff2 files that are not in the next/font subsets list.
```

#### page files
It looks like the default preloads every .js file in the build.  For sites that have alot of pages, this feels like an necessary burden on a user that could have limited mobile bandwidth.    I believe the default [next.js prefetch of files in viewport](https://nextjs.org/docs/pages/api-reference/components/link#prefetch) is probably optimal for the average user.
```
buildExcludes: [ /^((?!~offline).)*\.js$/ ]  // Exclude all .js files that do not contain ~offline in the path
```

### What to do
My opinion is that these are defaults out of the box if that is possible.  Documentation around a 'minimal' preload suggestion to protect users that use sentry, next/font or have large amount of pages could be good too:
```
    const withPWA = (await import('@ducanh2912/next-pwa')).default({
      dest: 'public',
      buildExcludes: [
        /\.map$/,                      // Exclude all .map files
        /^((?!~offline).)*\.js$/,  // Exclude all .js files that do not contain ~offline in the path
        /(?<!\.p)\.woff2$/,        // Exclude all .woff2 files that are not in the next/font subsets list
      ],
    });
```  

### Expected behavior

next-pwa:
* doesn't preload map files
* preloads only font files called out in next.js subsets list
* only preloads offline page (other pages are downloaded during viewport visible link behavior)

**Comment by DuCanhGH** [comment]
Thanks!

Let's break your point down a bit:

- `.map` files: Yeah, these files really don't matter for the users, so perhaps they should be excluded.
 
- Font files: your RegExp essentially means that we drop all font files except for `.p.woff2` if I understand it correctly. I think we should use `/\/_next\/static\/.*(?<!\.p)\.woff2/` instead - this will drop all non-`.p.woff2` files that belong to `next/font`, which probably means it won't be a breaking change for those who don't use `next/font`. I'd like to confirm that `.p` means prioritized though.
 
- `.js` files: the reason to consider excluding these files being the fact that they are preloaded by `next/link` on hover seems reasonable to me. However, considering the technical bits, excluding only JS files that include `~offline` seems really specific. If we were to introduce something that the user won't ever visit through `next/link` (just like `/~offline`) once more, we would have to change the defaults again - this is something I'd like to avoid to be honest. And `/~offline` probably has scripts that don't have `~offline` in its source link as well, so we'd break the page if we mistakenly exclude scripts that `/~offline` relies on. It is also worth nothing that the downloads seem to happen in the background (possibly in the service worker) so they probably won't block page load at all. All points considered, I think it would be best if we don't exclude JS files at all.

**Comment by Enalmada** [comment]
Makes sense.

* .map files: Yeah, I think it would be great to protect consumers from ever getting these automatically downloaded if it is possible.  There are also security issues to exposing these.  I think many will evaluate next-pwa with maps off on in an MVP and when they turn maps on later in prod (possibly unintentionally like me when I loaded sentry) for improved debugging there is a real risk they wont realize they all get in the consumer preload.
 
* Font files:  agreed `/\/_next\/static\/.*(?<!\.p)\.woff2/` makes much more sense.  I can't find any official documentation on the ".p" but as I look through next.js code I see [tests](https://github.com/search?q=repo%3Avercel%2Fnext.js+.p.woff2&type=code) that indicate the `.p` is probably also short for "preload". 
 
 * `.js` files: This is certainly the most opinionated one.  Small site may prefer everything preloaded.  It is really just a potentially unnecessary network resources issue on server and client as number of pages grows over time, especially over [64](https://github.com/DuCanhGH/next-pwa/blob/master/packages/next-pwa/src/cache.ts#L55).  Fortunately this is easy to configure.  Part of me wonders if the docs should be a bit stronger worded on what is happening in the background, perhaps a tip for larger sites with page sizes beyond max cache side to consider a more specific whitelist but I don't think this is a huge deal.

**Comment by DuCanhGH** [comment]
@Enalmada yeah, perhaps we can update the docs a bit regarding precaching `.js` files. There are `.next/app-build-manifest.json` and `.next/build-manifest.json`, which are really detailed regarding JS files that pages would use, but I don't know how the user would read them in `next.config.js`, so it is somewhat a shame.
