### ISSUE TITLE
[Feature request]: register a custom service worker file 

### ISSUE THREAD

**Issue by MrMelon1232** [DuCanhGH/next-pwa#107]
### Which project is this feature idea for?

@ducanh2912/next-pwa

### Describe the feature you'd like to request

Hi I was just wondering how to target a service worker file that will help generate the sw.js file. This is an option in next-pwa package in the next.config.js file where you can target the source of that file.

### Describe the solution you'd like

Have an option to specify the source of the service worker file in next.config.js file under here: 
const withPWA = require("@ducanh2912/next-pwa").default({
  dest: "public",
swSrc: “sw file path” //something like this 
}):

### Describe alternatives you've considered

None

**Comment by DuCanhGH** [comment]
Use `workboxOptions.swSrc`.

**Comment by MrMelon1232** [comment]
Hi, i get this error now: Please check your InjectManifest plugin configuration:
[WebpackInjectManifest] 'babelPresetEnvTargets' property is not expected to be here. Did you mean property 'manifestTransforms'?

This is my config: 
const withPWA = require("@ducanh2912/next-pwa").default({
  dest: "public",
  workboxOptions: {
    swSrc: "service-worker.js",
  },
});

module.exports = withPWA({
  reactStrictMode: true,
  transpilePackages: ["gsap"],
});

**Comment by DuCanhGH** [comment]
@MrMelon1232 crap, seems that `InjectManifest` doesn't support `babelPresetEnvTargets`. This error is caused by our adding `babelPresetEnvTargets` if `browserslist` is set (it always is, btw). Will fix soon :)
Impressive that noone has noticed that all this time though...

**Comment by MrMelon1232** [comment]
@DuCanhGH I appreciate quick response, would you have a possible ETA for this fix ? Also great work! Its very appreciated especially PWA apps being so effective and next-pwa being practically abandoned :)

**Comment by DuCanhGH** [comment]
@MrMelon1232 right now :) Also, thanks!

**Comment by DuCanhGH** [comment]
@MrMelon1232 done in `next-pwa@9.7.2` :)

**Comment by MrMelon1232** [comment]
@DuCanhGH can confirm this is working, thanks a lot!
