### ISSUE TITLE
[Feature request]: Use app offline

### ISSUE THREAD

**Issue by hdadr** [DuCanhGH/next-pwa#112]
### Describe the feature you'd like to request

I wish not to only have a fallback page when the app is offline, but to be able to use it fully (navigate to different pages) because at first it downloads all the data it needs when the site is visited. But later it can serve the app from the indexDB. 
Is there a way to do it?

### Describe the solution you'd like

I want a navigable app to be used offline.

### Describe alternatives you've considered

I considered to build the app in a way that it only uses the offline page and serve all the request of the user, but it makes it 100x harder.

**Comment by mauriciabad** [comment]
Totally agree. Real offline means that the app works without internet, and it is just missing the latest data. Like any native app. 

Only caching the already visited places, is not offline mode in my opinion.

**Comment by DuCanhGH** [comment]
@hdadr after you visit the pages, they will be automatically cached by default, which means that the next time you visit them offline, their cached versions will be served instead of a fallback

**Comment by DuCanhGH** [comment]
@mauriciabad I'm not sure how you expect `next-pwa` to straight up go and precache every single page beforehand. Like, there's nothing available to the plugin. If anything, it should be on you to manually precache all the pages using a custom worker, `caches`, and `fetch`.

**Comment by timothymiller** [comment]
> @mauriciabad I'm not sure how you expect `next-pwa` to straight up go and precache every single page beforehand. Like, there's nothing available to the plugin. If anything, it should be on you to manually precache all the pages using a custom worker, `caches`, and `fetch`. This will be run every time the service worker is updated, essentially equal to updating a native app.

I get where this is coming from. For this type of functionality, a native app is usually required. I use this library in my project for the web app, but offline functionality available in the native app

https://github.com/timothymiller/t4-app

**Comment by DuCanhGH** [comment]
@timothymiller yeah that's cool. I wish we could read Next.js's pages manifests, but here we are. Perhaps we could check for their existence with `Promise` and `setTimeout`, but I'd rather avoid bringing those kind of crap into the codebase.

**Comment by mauriciabad** [comment]
Actually Next server components make it specially hard because if it was all ran in the client, you could just cache the API requests and the app would work totally fine offline (as long as all the SPA's scripts are loaded and fetched data already stored in the device). I have no Idea about how this could be achieved with Next.js...

**Comment by DuCanhGH** [comment]
@mauriciabad in `next-pwa`'s default `runtimeCaching`, we have two separate entries for RSC, which are `"pages-rsc-prefetch"` and `pages-rsc`. To get those RSC responses you'd have to dive into some internal Next.js code to see how the framework does it though.

**Comment by flyingwolf1701** [comment]
This is all super interesting. My biggest problem is that while I go offline, I can visit 1 or sometimes 2 pages, but after that I get all these errors in my network saying that manifest failed to fetch. 

![image](https://github.com/DuCanhGH/next-pwa/assets/92654334/5d2e4adf-f3f9-4140-ba43-21c17cdf7f8a)

Do you have any idea why that is the case? I figure if I can just get the dang thing to NOT try and fetch when I am offline I have a good chance of figuring this out.

**Comment by hdadr** [comment]
I had the same problem as flyingwolf. I now moved to vitejs and zero config pwa plugin. It works offline after the initial app load.

**Comment by flyingwolf1701** [comment]
> I had the same problem as flyingwolf. I now moved to vitejs and zero config pwa plugin. It works offline after the initial app load.

I think @DuCanhGH has done an incredible job maintaining and rebuilding this package, I am beginning to realize that Next.js (or Remix.run for that matter) doesn't play nice with offline-first.

**Comment by hdadr** [comment]
That's also the conclusion where I arrived.

**Comment by flyingwolf1701** [comment]
> That's also the conclusion where I arrived.

@hdadr  What package did you end up using on your react/vite app?

**Comment by hdadr** [comment]
Yes, react (react-router-dom for routing) vite, and for pwa plugin: https://github.com/vite-pwa/vite-plugin-pwa

**Comment by DuCanhGH** [comment]
@flyingwolf1701 just realized I forgot to answer your question (was going through the repo's issues and closing some). That's probably because we use NetworkFirst for most of our default runtimeCaching array, which tries to fetch the thing first before falling back to the cache. Perhaps you can copy it and and change everything to CacheFirst, but I wouldn't recommend this because some things just don't play nice with that caching strategy.

**Comment by flyingwolf1701** [comment]
> @flyingwolf1701 just realized I forgot to answer your question (was going through the repo's issues and closing some). That's probably because we use NetworkFirst for most of our default runtimeCaching array, which tries to fetch the thing first before falling back to the cache. Perhaps you can copy it and and change everything to CacheFirst, but I wouldn't recommend this because some things just don't play nice with that caching strategy.

Thank you so much! I appreciate all your hard work on this package! Yeah, I have tried all that and I have found that you are correct. I think its a matter of using the right tool for the job. And Next.js is not the right tool for something that is offline first. Its my fault for trying to make it do something it can't. 

I really commend you on keeping this thing running and working with all the rapid changes in Next.js tech!

**Comment by DuCanhGH** [comment]
@flyingwolf1701 thanks!
