### ISSUE TITLE
Getting a TypeError on node_modules/workbox-webpack-plugin/build/generate-sw.js

### ISSUE THREAD

**Issue by MendyLanda** [DuCanhGH/next-pwa#116]
In the process of a massive overhaul to my applications, I started working on the one using next-pwa and it errors with this message:
<img width="1180" alt="image" src="https://github.com/DuCanhGH/next-pwa/assets/54242706/96301c04-d0cb-4cd3-bfbe-dc10fb05a553">

If I set disabled to true in the pwa config it still the same, even after removing the withPwa wrapper still the same. It only goes away after completly removing the import from withPWA 
```ts
// import withPWA from "@ducanh2912/next-pwa";
```

my next.config.mjs: (p.s. I confirmed `withSentryConfig` is not causing the issue)
```ts
import withPWA from "@ducanh2912/next-pwa";
import { withSentryConfig } from "@sentry/nextjs";

// Importing env files here to validate on build
const { env } = await import("./src/env.mjs");

/** @type {import("next").NextConfig} */
const config = {
  i18n: {
    /** @type {SupportedLocale[]} */
    locales: ["en", "he"],
    /** @type {DefaultLocale} */
    defaultLocale: "en",
  },
  reactStrictMode: true,
  /** Enables hot reloading for local packages without a build step */
  transpilePackages: ["@kangaroo/api", "@kangaroo/ui", "@kangaroo/lib"],
  /** We already do linting and typechecking as separate tasks in CI */
  eslint: { ignoreDuringBuilds: !!process.env.CI },
  typescript: { ignoreBuildErrors: !!process.env.CI },
  modularizeImports: {
    "@phosphor-icons/react": {
      // see https://github.com/phosphor-icons/react/issues/45#issuecomment-1488729840
      transform: "@phosphor-icons/react/{{member}}",
    },
  },
};

/** @type {import("@ducanh2912/next-pwa").PluginOptions} */
const pwaConfig = {
  dest: "public",
};

const sentryConfig = [
... // not interesting, I tried without sentry and still didn't work.
];

export default withSentryConfig(
  withPWA(pwaConfig)(config),
  ...sentryConfig,
);
```

versions:
```ts
  {
    "webpack": "^5.89.0",
    "@ducanh2912/next-pwa": "^9.7.2",
  }
```

**Comment by DuCanhGH** [comment]
That's weird. Is this issue reproducible with `next.config.js` (the CommonJS one)? Please give it a try, so I can pinpoint the issue more efficiently. Thanks!

**Comment by MendyLanda** [comment]
> That's weird. Is this issue reproducible with `next.config.js` (the CommonJS one)? Please give it a try, so I can pinpoint the issue more efficiently. Thanks!

The issue persisted even with the `.js` config. However, after updating multiple packages in the project it's now working. Hard to say what caused it, but since no one here or on the original repo has encountered this issue before I think chances of it happening are very low.

Closing this for now.

Thank you @DuCanhGH for maintaining this package ❤️

**Comment by DuCanhGH** [comment]
@MendyLanda there's a chance it's a package manager issue :)
