### ISSUE TITLE
[Bug - next-pwa]: Cannot fallback to cache when using Network First

### ISSUE THREAD

**Issue by nandotmbn** [DuCanhGH/next-pwa#132]
### Provide environment information

"next": "13.5.6",
"@ducanh2912/next-pwa": "^10.1.0",
"axios": "^1.5.0",
"@tanstack/react-query": "^4.33.0",

I'm using Node 18.17.0

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code help us address them faster

--

### To reproduce

--

### Describe the bug

```js
{
	urlPattern: ({ sameOrigin, url: { pathname } }) => {
		if (!sameOrigin || pathname.startsWith("/api/auth/callback")) {
			return false;
		}

		if (pathname.startsWith("/api/")) {
			return true;
		}

		return false;
	},
	handler: "NetworkFirst",
	method: "GET",
	options: {
		cacheName: "apis",
		expiration: {
			maxEntries: 16,
			maxAgeSeconds: 24 * 60 * 60, // 24 hours
		},
		networkTimeoutSeconds: 5, // fallback to cache if API does not response within 10 seconds
	},
},
```

### Expected behavior

I want to use HTTP Request from the cache that has been saved.

<img width="741" alt="Screen Shot 2024-01-06 at 15 12 47" src="https://github.com/DuCanhGH/next-pwa/assets/66873366/59f5d1af-b4b6-4272-9917-2e48a88be384">

But when offline, the HTTP Request cannot be executed and the cache cannot be retrieved either.
I use Axios and TanStack Query as the HTTP Request Handler and Query State Management.

<img width="663" alt="Screen Shot 2024-01-06 at 15 13 12" src="https://github.com/DuCanhGH/next-pwa/assets/66873366/35ae5e6a-2d99-4c02-91fc-550d4ff78545">

After 5 seconds, there is no change, still loading.

Is there a way that I might not know from the documentation of this module?

**Comment by nandotmbn** [comment]
Oh my bad...
TanStack Query has a big impact on Fetching Data. It will be disable query when offline.
If you need to query regardless network status, you can configure QueryClient like code below

```js
QueryClient({
  defaultOptions: {
    queries: {
      networkMode: "always",
    },
  },
})
```

**Comment by DuCanhGH** [comment]
@nandotmbn 💀 Alright
