### ISSUE TITLE
[Bug - next-pwa]:  `__dirname` is not defined when using 10.2.0 and nextjs 14

### ISSUE THREAD

**Issue by arvinxx** [DuCanhGH/next-pwa#134]
### Provide environment information

NextJS: 14.0.4
@DuCanhGH/next-pwa: 10.2.0

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code help us address them faster

https://github.com/lobehub/lobe-chat/pull/1011

### To reproduce

```
git clone https://github.com/lobehub/lobe-chat

git checkout arvinxx-patch-1

bun run i

npm run build
```

### Describe the bug

```bash
ReferenceError: __dirname is not defined
16:33:20.398 | at createContext (file:///vercel/path0/node_modules/@ducanh2912/next-pwa/dist/index.js:1:15434)
16:33:20.398 | at Object.webpack (file:///vercel/path0/node_modules/@ducanh2912/next-pwa/dist/index.js:2:6271)
16:33:20.398 | at Object.webpack (/vercel/path0/node_modules/@next/bundle-analyzer/index.js:23:29)
16:33:20.398 | at getBaseWebpackConfig (/vercel/path0/node_modules/next/dist/build/webpack-config.js:1738:32)
16:33:20.398 | at async Promise.all (index 1)
16:33:20.398 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:147:20)
16:33:20.398 | at async webpackBuildImpl (/vercel/path0/node_modules/next/dist/build/webpack-build/impl.js:132:21)
16:33:20.398 | at async webpackBuild (/vercel/path0/node_modules/next/dist/build/webpack-build/index.js:165:16)
16:33:20.398 | at async /vercel/path0/node_modules/next/dist/build/index.js:695:115
16:33:20.398 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:147:20)
16:33:20.423 | error: script "build" exited with code 1
16:33:20.427
```

### Expected behavior

build success

### Screenshots (if relevant)

![image](https://github.com/DuCanhGH/next-pwa/assets/28616219/3172501e-d162-4b2d-8aab-2f7015fcf1a1)

![image](https://github.com/DuCanhGH/next-pwa/assets/28616219/94e7e6ac-9ece-444d-aad5-6be79cb6c32e)

**Comment by DuCanhGH** [comment]
Ah. Yes. The joy of handling both module systems...
I've fixed it in 10.2.1 and added a test. Give it a try! Sometimes the package goes under quite a refactor, and with not-so-advanced tests, things like this can happen. Really sorry for that. I recommend pinning your dependencies so as to avoid weird bugs suddenly crashing your build, but that's for you to decide :)

**Comment by arvinxx** [comment]
>  I recommend pinning your dependencies so as to avoid weird bugs suddenly crashing your build

Thanks for your suggestion. I'd like to trust open source community and keep dependencies latest. So I can get latest update and bug fix automatic. And I also will know whether the latest dependency work correct. If not , I can report it asap like this time :)

**Comment by DuCanhGH** [comment]
@arvinxx 
> I'd like to trust open source community and keep dependencies the latest. So I can get latest update and bug fix automatic.

Alright, cool :)
