### ISSUE TITLE
[Bug - next-pwa]: Having a hard time deploying to production

### ISSUE THREAD

**Issue by mubarakone** [DuCanhGH/next-pwa#138]
### Provide environment information

"@ducanh2912/next-pwa": "^10.1.0",
"next": "latest",
"next-compose-plugins": "^2.2.1",
"next-contentlayer": "0.3.4",

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code help us address them faster

https://github.com/mubarakone/tailwind-css-starter-blog

### To reproduce

Deploying to Vercel 

### Describe the bug

When I deploy for production, the PWA install icon does not show up on the address bar. And when I ran Lighthouse, the PWA was not installable because the manifest.json file wasn't recognizable.

Then when I checked the logs on Vercel, I see that the manifest.json was recognized, but it came with these 401 Unauthorized warning errors.

![image](https://github.com/DuCanhGH/next-pwa/assets/52806204/11f8bdd4-5a42-4de7-bbcf-aa7c2c9e1b2c)

So I looked to the docs, and found a potential solution:

![image](https://github.com/DuCanhGH/next-pwa/assets/52806204/de5609e8-4526-4b8f-985f-a34de9d1940f)

I didn't specify where, but judging by the syntax, I figured it would be located in the `next.config.js` file rather than `manifest.json`. When I implemented this, it looks like it doesn't recognize this:

![image](https://github.com/DuCanhGH/next-pwa/assets/52806204/d38f13c2-94db-48bc-a09c-e6ff9449f884)

But after some modifications, it is now looking much better:

![image](https://github.com/DuCanhGH/next-pwa/assets/52806204/140fd5f3-12cf-496f-90c1-62e29015c840)

However when I try to run on dev environment, I get this:
```
  ▲ Next.js 14.0.4
   - Local:        http://localhost:3000

 ✓ (pwa) Compiling for server...
 ✓ (pwa) Compiling for server...
 ✓ (pwa) Compiling for client (static)...
 ○ (pwa) Service worker: C:\Users\mubar\Documents\1to1 next app\zerodev-test\tailwind-css-starter-blog\public\sw.js
 ○ (pwa)   URL: /sw.js
 ○ (pwa)   Scope: /
 ○ (pwa) Building in development mode, caching and precaching are disabled for the most part. This means that offline support is disabled, but you can continue developing other functions in service worker.
Warning: Contentlayer might not work as expected on Windows
 ⨯ Please check your GenerateSW plugin configuration:
[WebpackGenerateSW] '0' property is not expected to be here.
 ⨯ Please check your GenerateSW plugin configuration:
[WebpackGenerateSW] '0' property is not expected to be here.
 ✓ Ready in 8.7s
Contentlayer config change detected. Updating type definitions and data...
successCallback C:/Users/mubar/Documents/1to1 next app/zerodev-test/tailwind-css-starter-blog/.contentlayer
SuccessCallbackError: Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
 ○ Compiling / ...
 ⨯ Please check your GenerateSW plugin configuration:
[WebpackGenerateSW] '0' property is not expected to be here.
 ✓ (pwa) Compiling for client (static)...
 ○ (pwa) Service worker: C:\Users\mubar\Documents\1to1 next app\zerodev-test\tailwind-css-starter-blog\public\sw.js
 ○ (pwa)   URL: /sw.js
 ○ (pwa)   Scope: /
 ○ (pwa) Building in development mode, caching and precaching are disabled for the most part. This means that offline support is disabled, but you can continue developing other functions in service worker.
 ⨯ Please check your GenerateSW plugin configuration:
[WebpackGenerateSW] '0' property is not expected to be here.
 ⨯ Please check your GenerateSW plugin configuration:
[WebpackGenerateSW] '0' property is not expected to be here.
 ⨯ Error: ENOENT: no such file or directory, open 'C:\Users\mubar\Documents\1to1 next app\zerodev-test\tailwind-css-starter-blog\.next\fallback-build-manifest.json'
    at readFileSync (node:fs:453:20)
    at loadManifest (C:\Users\mubar\Documents\1to1 next app\zerodev-test\tailwind-css-starter-blog\node_modules\next\src\server\load-manifest.ts:12:43)
    at loadManifestWithRetries (C:\Users\mubar\Documents\1to1 next app\zerodev-test\tailwind-css-starter-blog\node_modules\next\src\server\load-components.ts:75:26)
    at loadDefaultErrorComponentsImpl (C:\Users\mubar\Documents\1to1 next app\zerodev-test\tailwind-css-starter-blog\node_modules\next\src\server\load-default-error-components.ts:66:20)
    at DevServer.getFallbackErrorComponents (C:\Users\mubar\Documents\1to1 next app\zerodev-test\tailwind-css-starter-blog\node_modules\next\src\server\dev\next-dev-server.ts:838:12)
    at DevServer.renderErrorToResponseImpl (C:\Users\mubar\Documents\1to1 next app\zerodev-test\tailwind-css-starter-blog\node_modules\next\src\server\base-server.ts:3363:34)
    at DevServer.renderToResponseImpl (C:\Users\mubar\Documents\1to1 next app\zerodev-test\tailwind-css-starter-blog\node_modules\next\src\server\base-server.ts:3096:24)
    at DevServer.pipeImpl (C:\Users\mubar\Documents\1to1 next app\zerodev-test\tailwind-css-starter-blog\node_modules\next\src\server\base-server.ts:1568:21)
    at DevServer.NextNodeServer.handleCatchallRenderRequest (C:\Users\mubar\Documents\1to1 next app\zerodev-test\tailwind-css-starter-blog\node_modules\next\src\server\next-server.ts:946:7)
    at DevServer.handleRequestImpl (C:\Users\mubar\Documents\1to1 next app\zerodev-test\tailwind-css-starter-blog\node_modules\next\src\server\base-server.ts:1353:9) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\mubar\\Documents\\1to1 next app\\zerodev-test\\tailwind-css-starter-blog\\.next\\fallback-build-manifest.json' 
}
```

Of course the project also fails to build for production as well

### Expected behavior

Both dev and prod environment should work.

**Comment by DuCanhGH** [comment]
![image](https://github.com/DuCanhGH/next-pwa/assets/75556609/0cd3ebd5-75d6-4f49-bab9-d47003cace43)

Just ask yourself if you even know JavaScript.

Also that's not even related to the original issue.

**Comment by maverickdude** [comment]
@DuCanhGH you didn't need to be rude.

@mubarakone update your `next.config.js` as following:

```
const withPWA = require('@ducanh2912/next-pwa').default({
  dest: "public",
  workboxOptions: {
    mode: "production"
  }
})
```

**Comment by DuCanhGH** [comment]
@maverickdude I didn't have to be rude, and I was wrongly so nonetheless, but I don't regret that at all. Usually I do tolerate questions that make next to no sense, but this one was just too bad, and I was under a shitty fever that day. Quite a nice combination, I'd say.

First thing first, let's look at how they handled the case. Their first reaction to a 401 HTTP response was like this must have been caused by `next-pwa`?? Like why would it authenticate something? Usually, a cached response is a success one and wouldn't be an 401 one. Then, they turned to the docs. Cool, that was a nice move. But I just couldn't fathom how they came up with the idea that making Workbox run in production mode, which is the default when you deploy anyway, would fix their issue. Then they tried to do it. Now this is what triggered me the most. Why would a developer who have begun building a product think that `workboxOptions.mode` is a valid JS object key? I mean, I wouldn't have blamed them had they tried `"workboxOptions.mode"`, since one could interpret the docs that way too, but they turned to removing `.mode` altogether. That was enough to push me over the edge. The validation error from Workbox was cryptic, however, so that wasn't really their issue.

Again, I could've been nicer, but that wouldn't be something I would expect from a bad-tempered guy under a fever.
