### ISSUE TITLE
[Bug - next-pwa]: getting Uncaught (in promise) add-to-cache-list-conflicting-entries: add-to-cache-list-conflicting-entries

### ISSUE THREAD

**Issue by aidotaosm** [DuCanhGH/next-pwa#139]
### Provide environment information

    "@ducanh2912/next-pwa": "10.2.0",
    "next": "^14.1.0",

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code help us address them faster

n/a

### To reproduce

Updated from 10.1.0 to 10.2.0

### Describe the bug

After Updated from 10.1.0 to 10.2.0 getting the below error message, and for this the whole service worker breaks functionality.
![image](https://github.com/DuCanhGH/next-pwa/assets/28359940/3ad766ef-b6b0-48a5-8518-b0c603ffa116)

### Expected behavior

This should not happen

### Additional information (if relevant)
This is the app, it's currently using version 10.1.0 for the above reason. Sharing this link so the caching can be seen form developer tools.
https://nextgen-pokemon-tcg.pro/

_No response_

**Comment by aidotaosm** [comment]
Thanks, I figured out the problem,

The package is pre-caching the fallback image and then the same image is again set to be cached from the public folder causing the error.

But,

At v10.1.0 my public route was not being pre-cached (a bug I guess). Thus the image was being cached once for the public folder.
But after updating to v10.2 the public folder is being properly cached causing the aforementioned error.

The adding my falback image's url to publicExcludes array allowed me to build upon v10.2.

Thanks either way!

**Comment by DuCanhGH** [comment]
@aidotaosm 
> At v10.1.0 my public folder was not being pre-cached (a bug I guess). Thus the image was being cached once for the fallback image.
What?
Anyway, seems that that change really was a breaking change... Really sorry for that.

**Comment by aidotaosm** [comment]
Having the same image in public folder and set as fallback image causes this issue. The temporary fix is to mention the fallback image into publicexcludes array.

**Comment by DuCanhGH** [comment]
@aidotaosm 
> Having the same image in public folder and set as fallback image in next config causes this issue.

Yes. Just that. Just what I needed. Will fix soon.

**Comment by DuCanhGH** [comment]
@aidotaosm should be fixed in 10.2.5. Give it a try!
