### ISSUE TITLE
[Feature request]: Register Web Periodic Background Synchronization 

### ISSUE THREAD

**Issue by MrMelon1232** [DuCanhGH/next-pwa#140]
### Describe the feature you'd like to request

Would it be possible to register a periodic background sync as mentioned in this thread [https://developer.mozilla.org/en-US/docs/Web/API/Web_Periodic_Background_Synchronization_API](url) instead of manually registering it with the service worker.

### Describe the solution you'd like

Have the option to register a periodic background sync in configs.

### Describe alternatives you've considered

Having to register the service worker manually so that the periodic background sync can be registered as shown in the linked thread.

**Comment by DuCanhGH** [comment]
Isn't it that the code in that thread just works? I think it is fine for use with `next-pwa`. As for the "periodicsync" listener, there's no choice but to use InjectManifest with a service worker source. Sorry about that.

**Comment by DuCanhGH** [comment]
@MrMelon1232 just remembered that I had forgotten that `next-pwa` allows you to write a custom worker. So you can probably do something like this:
```ts
// @filename: workers/index.ts
declare const self: ServiceWorkerGlobalScope;
declare function fetchAndCacheLatestNews(): void;

self.addEventListener("periodicsync", (event) => {
  if (event.tag === "get-latest-news") {
    event.waitUntil(fetchAndCacheLatestNews());
  }
});
```
