### ISSUE TITLE
[Bug - next-pwa]: fallback file from public folder downloaded from CDN instead of Next server

### ISSUE THREAD

**Issue by FredTreg** [DuCanhGH/next-pwa#142]
### Provide environment information

Next: 14.1
@ducanh2912/next-pwa: 10.2.2

The issue does not occur in 9.7.2

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code help us address them faster

Not available

### To reproduce

Deploy your next app in standalone mode (i.e. not on vercel, using a custom node server) and use an `assetPrefix` next config option such as:

```
const withPWA = require('@ducanh2912/next-pwa').default({
  dest: 'public',
  disable: process.env.NODE_ENV !== 'production'
})

const isStaging = process.env.TARGET_ENV === 'staging'
const isProd = process.env.TARGET_ENV === 'prod'

const nextConfig = {
  assetPrefix: isStaging
    ? 'https://static-staging.coucou-de-france.fr'
    : isProd
      ? 'https://static.coucou-de-france.fr'
      : undefined,
  output: 'standalone'
}

module.exports = withPWA(nextConfig)
```

### Describe the bug

Not sure this is a bug or an intended breaking change from an earlier version, but after moving from 9.7.2 to 10.2.2, next-pwa displayed the following in my console:
```
Uncaught (in promise) bad-precaching-response: bad-precaching-response :: [{"url":"https://static.coucou-de-france.fr/public/fallback-8e5b7798448a30a7.js","status":404}]
    at Z.S (https://www.coucou-de-france.fr/workbox-c06b064f.js:1:16900)
    at async Z.U (https://www.coucou-de-france.fr/workbox-c06b064f.js:1:16452)
    at async Z.q (https://www.coucou-de-france.fr/workbox-c06b064f.js:1:7597)
```
It means that out of the 3 files generated by next-pwa in the public directory, two (sw.js and workbox-xxx.js) are downloaded from the Next server and one (fallback-xxxx.js) is downloaded from the `assetPrefix` (i.e. CDN) next.config.js URL.

### Expected behavior

Either this a a bug and the fallback file should be downloaded from Next (if I read the Next documentation correctly, assetPrefix does not apply to the public folder) or this is intended behavior for optimization and the generated fallback file should be made available on the assetPrefix URL in a public folder. In that case, I believe this should be documented.

**Comment by FredTreg** [comment]
**UPDATE 1**
For now, I upload the content of the public directory to my CDN as well.
I am fine with this workaround as this provide proper CDN caching for fallback.js (as the file name contains the hash).

** UPDATE 2**
After checking the network, I see that the `fallback-xxx.js` is downloaded twice, one initiated by the `sw.js` script and downloaded from the main server URL (200), and one initiated by the `workbox-xxx.js` script and downloaded from the `assetPrefix` URL (404 before I fixed it by uploading public to the CDN). So now I am really confused and I believe there is something wrong...

** UPDATE 3**
This made me think that maybe there should be two different settings instead of a single `dest` directory. For example :

* `bootstrapDestDir` with a default value of `public` (served directly from https://my.website.com)
* `assetsDestDir` with a default value of `.next/static/pwa` (served from ${assetPrefix}/_next/static/pwa)

But I am not sure about must be delivered from the main URL from a PWA specification standpoint.

**Comment by DuCanhGH** [comment]
@FredTreg there was a mistake in our refactoring to using a context as described in [the fix](https://github.com/DuCanhGH/next-pwa/commit/e5f1d14828d669e17e694e0a18bcfb2f8231a6b9). Give the new version a try!

**Comment by FredTreg** [comment]
Well, there is a change for sure, but I am still confused, now I get the error:
```
workbox-c06b064f.js:1 Uncaught (in promise) bad-precaching-response: bad-precaching-response :: [{"url":"https://static.coucou-de-france.fr/fallback-8e5b7798448a30a7.js","status":404}]
    at Z.S (https://www.coucou-de-france.fr/workbox-c06b064f.js:1:16900)
    at async Z.U (https://www.coucou-de-france.fr/workbox-c06b064f.js:1:16452)
    at async Z.q (https://www.coucou-de-france.fr/workbox-c06b064f.js:1:7597)
```
Meaning that the fallback-xxx.js file is still fetched from the CDN (i.e. static.coucou-de-france.fr in my example), though not from the public folder anymore. Note that the file as mentioned above in UPDATE 2 is still also downloaded from www.coucou-de-france.fr which is the main (i.e. next) server.

It means I still have to upload the public folder to my CDN, although no longer in a dedicated public folder. Reverting to 10.2.2 until the issue is clarified as to what should be downloaded from where (i.e. from the next server from the public/ folder mapped to the root of the origin server OR from the assetPrefix URL OR both as it seems to be the case for now)

**Comment by DuCanhGH** [comment]
@FredTreg 10.2.4 has been released. Give it a try! This patch specifically fixes `next-pwa` with `assetPrefix` and adds a test for that.
