### ISSUE TITLE
[Bug - next-pwa]: Does not work with turbopack (next dev --turbo)

### ISSUE THREAD

**Issue by Cybermb** [DuCanhGH/next-pwa#146]
### Provide environment information

next@14.1.0
@ducanh2912/next-pwa@10.2.5

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code help us address them faster

https://github.com/DuCanhGH/next-pwa/tree/master/examples/basic

### To reproduce

1. Add `--trubo` flag to start script in package.json
2. Start dev script

### Describe the bug

Service worker does not work when turbopack is enabled. Disabling it fixes the issue

### Expected behavior

Service worker should work when turbopack is enabled

**Comment by DuCanhGH** [comment]
See https://github.com/serwist/serwist/issues/54#issuecomment-1913445264.
