### ISSUE TITLE
Too many redirects for /.well-known/ folder

### ISSUE THREAD

**Issue by ilyagru** [DuCanhGH/next-pwa#150]
Hi, I'm not sure if this is right to open an issue here but... it seems that the service worker implementation clashes with folders at the root.

I want to host an apple verification file at `/.well-known/apple-file` but when I open the full URL in the browser, it redirects too many times and says (from service worker).

ANy ideas what the issue could be? Thanks!

<img width="1096" alt="Screenshot 2024-05-01 at 10 39 42" src="https://github.com/DuCanhGH/next-pwa/assets/18074511/7859db59-05a4-4d18-ac17-bafe5430ae49">

Next.js: ^14.2.2
@ducanh2912/next-pwa: ^10.2.6

**Comment by DuCanhGH** [comment]
@ilyagru there's not much info we can get out of this issue. Can you provide a reproduction? Thanks!

I can't see how the service worker would treat this file any different to how it does for other files, though.
