### ISSUE TITLE
[Docs]: This repo is not ranked on google

### ISSUE THREAD

**Issue by SH20RAJ** [DuCanhGH/next-pwa#157]
### Provide environment information

..

### Describe the problem

This repo isn't ranked on google because this repo is a forked repo despite of being so popular this isn't ranked yet.
Google doesn't prioritise the forked repos,
and lesser popular repos ar eon google

### Expected behavior

See https://www.google.com/search?q=site%3Ahttps%3A%2F%2Fgithub.com

**Comment by DuCanhGH** [comment]
...Not much I can do about that. GitHub probably inserts `<meta name="robots" content="noindex">` into forked repos' pages. Not that I've checked though. Still, if you search "next-pwa", the docs site is literally second only to the original `next-pwa`'s GitHub repo. Decent enough I'd say.
