### ISSUE TITLE
Will this work with Next 13?

### ISSUE THREAD

**Issue by laurencefass** [DuCanhGH/next-pwa#16]
Will this work with Next 13?

What about the new app folder?

Thanks!

**Comment by laurencefass** [comment]
For clarity: have you then modified this from the originating repo to work with app folder, and is it on feature parity with forked repo supporting only pages folder? Would be good to know what unique features your package offers over fork as the readme looks the same.

**Comment by DuCanhGH** [comment]
@laurencefass this forked package works with both `pages/` and `app/`. I've also listed [notable changes I've made](https://github.com/shadowwalker/next-pwa/issues/424#issuecomment-1401929790), and you can also check [the Releases tab](https://github.com/DuCanhGH/next-pwa/releases) for more information.
