### ISSUE TITLE
Found lockfile missing swc dependencies, patching... [Bug - next-pwa]: 

### ISSUE THREAD

**Issue by iamrishan** [DuCanhGH/next-pwa#162]
### Provide environment information

Build Failed
NextJS: 14.2.3

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code help us address them faster

npm run buid

### To reproduce

start new nextjs 14.2.3 app and add the pwa, try to build the app

### Describe the bug

Building successfully after uninstalling webpack and @ducanh2912/next-pwa

### Expected behavior

Should build successfully

### Screenshots (if relevant)

![Code_934QSqw6f7](https://github.com/user-attachments/assets/5bcbd484-7143-4272-9b16-d1ffb68f631c)

**Comment by DuCanhGH** [comment]
Uh... I fail to see how this is related to the project. Are you sure this is not just you? How about deleting your lockfile and running `npm i` again?

**Comment by iamrishan** [comment]
Thanks
