### ISSUE TITLE
recommendations for push notifications

### ISSUE THREAD

**Issue by laurencefass** [DuCanhGH/next-pwa#17]
Hi what is the best way to integrate push notifications into my PWA Next app?

Does this package provide it or do I need to add a different package to make that work?

If so, do you have any recommendations?

**Comment by DuCanhGH** [comment]
[Here is an example](https://github.com/DuCanhGH/next-pwa/tree/ebc4593953d456239a47b694c2dd621e57dfc24d/examples/web-push), though it was from the original repo and I haven't touched it much aside from converting the code to TS. But it should work nicely as an example, yeah. There's also [this resource](https://web.dev/notifications/).

**Comment by mjsisley** [comment]
As an FYI (this is likely beyond the scope of your fork):

Setup the example. Works great in chrome. But does not work on an iOS pwa out of the box.
Possibly related to https://github.com/shadowwalker/next-pwa/issues/474

Thanks for this fork btw!

**Comment by johanneskares** [comment]
I just deployed the example to Vercel and insane to see that it works on iOS now and sends a push notification.

**Comment by StephenMarkToms** [comment]
I couldn't agree more, just got back from doing a hackathon competition and we won because of PWA and push notifications. Another helpful article if anyone comes across it is this for a bare bones example of how to send from servers. https://devtails.xyz/@adam/how-to-setup-web-push-notifications-in-ios-safari

**Comment by MrlolDev** [comment]
> I just deployed the example to Vercel and insane to see that it works on iOS now and sends a push notification.

Could you show how u made it?
