### ISSUE TITLE
[Bug]: Pages are not cached in app directory

### ISSUE THREAD

**Issue by floatingdino** [DuCanhGH/next-pwa#18]
### Provide environment information

Versions:

next@13.3.4
@ducanh2912/next-pwa@8.3.0

Note Stackblitz/Codesandbox don't seem to work with Next App Directory.

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code help us address them faster

https://stackblitz.com/edit/nextjs-1vuor4

### To reproduce

- Clone this repo
- Install and run examples/basic (I needed to manually build next-pwa to run on my local)
- Open http://localhost:3000/appdir
- Turn on "offline mode" (Devtools / Application / Service Worker in Chrome)
- Refresh the page
- Click the link to go to the "About" page
- Note the offline fallback screen appears

### Describe the bug

App directory pages other than the landing page are not cached.

It seems that since the App Router returns JSON payloads when requesting page URLs rather than HTML, these pages cannot be cached with the current setup. Unsure if it's fixable since it seems tricky to separately cache the page HTML and JSON for direct and router navigation.

### Expected behavior

Pages are cached and accessible offline for app directory usage.

**Comment by DuCanhGH** [comment]
Yeah it is quite a pain tbh, Next sends `text/html` content on normal page requests but sends `text/x-component` (which is RSC) for client-side transitions though the requests look... identical? There's probably nothing I can point `workbox` to so that it can differentiate these responses. I don't know, but I've been trying to bring offline support to `app/`, though very slowly as I'm really busy with other stuff as well...

**Comment by floatingdino** [comment]
Appreciate your response - with a little digging, it seems like Next returns the RSC JSON payload when your request includes the header `RSC: 1`. Another interesting thread is that when the output is set to `export` the build seems to split pages into a separate HTML and TXT file. I'm keen to get this sorted out if possible as I have a couple of projects that need offline support and I'd love to use App Directory.
Let me know if you have any further thoughts that I could help with.

**Comment by DuCanhGH** [comment]
@floatingdino can you try copying `cache.ts` in `packages/next-pwa`, but add this part before the entry with `cacheName` others and after the entry with `cacheName` apis?
```js
{
    urlPattern: ({ request, url, sameOrigin }) => {
      if (request.headers.get("RSC") !== "1" || !sameOrigin) return false;
      const pathname = url.pathname;
      if (pathname.startsWith("/api/")) return false;
      return true;
    },
    handler: "NetworkFirst",
    options: {
      cacheName: "pages-rsc",
      expiration: {
        maxEntries: 32,
        maxAgeSeconds: 24 * 60 * 60, // 24 hours
      },
      matchOptions: {
        ignoreVary: true,
      },
    },
  },
```
We are ignoring `Vary` here, which means that we don't care about `Next-Router-State-Tree` (not ignoring this header makes offline support very inefficient - as in it basically never matches these RSC responses) - and it may cause trouble, so do this at your own risk...

**Comment by floatingdino** [comment]
@DuCanhGH awesome! That seems to work. However, navigating to a route that's not cached doesn't return the offline fallback at this stage 🤔

**Comment by DuCanhGH** [comment]
@floatingdino what behavior are you seeing? Thanks!

**Comment by floatingdino** [comment]
@DuCanhGH After a bit more investigation, it seems like an issue when you have RSC data for a page but not the HTML (this can happen when the `next/link` prefetches a link that's on screen but not clicked). Clicking the link when offline unmounts the old route (perhaps it mounts the new layouts, but my project doesn't have much in the layouts) but doesn't display the new page or the offline fallback. Also seems like the RSC prefetch data is different to the data it gets when actually visiting a route (prefetches have request header `Next-Router-Prefetch = 1`) and trying to use prefetch data to navigate to a route fails. I've added another entry to the `runtimeCaching` to put prefetches in another bucket at this stage, which now seems to show the offline fallback when trying to retrieve a page that's prefetch is cached but not the page itself.

**Comment by DuCanhGH** [comment]
@floatingdino `next-pwa` 8.5.0 should now cache RSC prefetches separately from RSC requests :)

> I've added another entry to the runtimeCaching to put prefetches in another bucket at this stage, which now seems to show the offline fallback when trying to retrieve a page that's prefetch is cached but not the page itself.

I'm not seeing this issue to be honest, I've tried cleaning Cache Storage and letting Next prefetch before going offline and visiting the page and there were no such issue :(
