### ISSUE TITLE
[Bug]: seems not working on next 13.4.2

### ISSUE THREAD

**Issue by joacub** [DuCanhGH/next-pwa#21]
### Provide environment information

Files seems to be not served. Don’t know if is related to next or is the module. But files in public are not been served 

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code help us address them faster

No response 

### To reproduce

App dir

### Describe the bug

Not working 

### Expected behavior

Working

**Comment by DuCanhGH** [comment]
I can't reproduce this issue.
![image](https://github.com/DuCanhGH/next-pwa/assets/75556609/2f65da35-3b48-4386-9903-4721ba832547)
This is a  `create-next-app` template used with this package, and as you can see all the assets are served correctly.

**Comment by joacub** [comment]
> Please provide a reproduction, as I can't reproduce this issue.
> ![image](https://user-images.githubusercontent.com/75556609/238003379-2f65da35-3b48-4386-9903-4721ba832547.png)
> This is a `create-next-app` template used with this package, and as you can see all the assets are served correctly.

Implement in that example next-intl 

https://next-intl-docs.vercel.app/

that may be the cause

**Comment by joacub** [comment]
I will close this, and for others with the same problem, is happening because of the middleware redirection.

you can avoid this by using the matcher like this:
```
  matcher: ['/((?!api|_next|.*\\..*).*)']
```

**Comment by ambelong** [comment]
> I will close this, and for others with the same problem, is happening because of the middleware redirection.
> 
> you can avoid this by using the matcher like this:
> 
> ```
>   matcher: ['/((?!api|_next|.*\\..*).*)']
> ```

Having the same issue with middleware. But when I add
`  matcher: ["/((?!api|_next|.*\\..*).*)"],`

I have a reload going forever.
