### ISSUE TITLE
[Docs]: Add sponsor for this fork

### ISSUE THREAD

**Issue by maiconcarraro** [DuCanhGH/next-pwa#29]
### Provide environment information

None

### Whose documentation is this feedback for?

@ducanh2912/next-pwa

### Describe the problem

You're doing an amazing work, how can I support you?

### Expected behavior

Be able to buy a coffee fro you

**Comment by DuCanhGH** [comment]
Thank you, I will consider adding that.

Honestly though, I don't really like the idea. I forked `next-pwa` to allow the community to continue creating PWAs with Next.js easily and securely - and I don't plan to make money from it. I'd love it if you can use the money to help those in need instead. [The core-js guy](https://github.com/zloirock/core-js/blob/master/docs/2023-02-14-so-whats-next.md), perhaps? I hope that this doesn't come off as being rude.

Thanks for the support!

**Comment by maiconcarraro** [comment]
Good call ✅ and thank you again for taking the lead here
