### ISSUE TITLE
[Bug - next-pwa]: Not working

### ISSUE THREAD

**Issue by allestaire** [DuCanhGH/next-pwa#30]
### Provide environment information

There are no install icon came out on the address bar

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code help us address them faster

Just install the package and followed the steps

### To reproduce

Here is the next.config.js
```js
/** @type {import('next').NextConfig} */

const withPWA = require("@ducanh2912/next-pwa").default({
  dest: "public",
});


const nextConfig = {
  experimental: {
    appDir: true,
  },
  env: {
    BASE_URL: process.env.BASE_URL
  }
}

module.exports = withPWA(nextConfig)

```

### Describe the bug

PWA install icon not showing

### Expected behavior

Should show install icon

### Screenshots (if relevant)

<img width="244" alt="Screen Shot 2023-06-12 at 11 29 45 AM" src="https://github.com/DuCanhGH/next-pwa/assets/68372409/c86669c2-eabb-46b8-9ae4-881f5bb361bd">

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T8101
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.4.4
      eslint-config-next: 13.4.0
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4

warn  - Latest canary version not detected, detected: "13.4.4", newest: "13.4.5".
        Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
        Read more - https://nextjs.org/docs/messages/opening-an-issue

**Comment by DuCanhGH** [comment]
I can't reproduce with our `examples/basic` (which is a just barebone Next.js app) on Chromium 114.0.5735.106:
![image](https://github.com/DuCanhGH/next-pwa/assets/75556609/82f06305-8804-41b1-a61b-40810a021c2c)

**Comment by allestaire** [comment]
Thanks for providing an example @DuCanhGH , will diagnose more and see which causes the problem :)

**Comment by allestaire** [comment]
Service worker was installed and running, but still the installation button is not showing.

<img width="672" alt="Screen Shot 2023-06-14 at 10 30 10 AM" src="https://github.com/DuCanhGH/next-pwa/assets/68372409/9440985d-67d6-4cb6-bba2-e214e06b8456">

**Comment by allestaire** [comment]
Just got solve the problem, it needs a `manifest.json` which is not added on the documentation, only if next version 9 below. but seeing the example, which has `manifest.json` which is I guess needed to be on the project even on higher version.
Now it works fine now :)

<img width="600" alt="Screen Shot 2023-06-14 at 11 18 36 AM" src="https://github.com/DuCanhGH/next-pwa/assets/68372409/48765941-1a57-4fd6-b599-6597b3959f03">
<img width="596" alt="Screen Shot 2023-06-14 at 11 19 54 AM" src="https://github.com/DuCanhGH/next-pwa/assets/68372409/757a1397-ae42-4770-9c02-b3d193cd8651">

**Comment by DuCanhGH** [comment]
@allestaire yeah you need to have `manifest.json` to have that, I thought your problem was that the service worker wasn't properly installed.

I did mention adding `manifest.json` in `next-pwa`'s Getting started section though!

**Comment by allestaire** [comment]
> @allestaire yeah you need to have `manifest.json` to have that, I thought your problem was that the service worker wasn't properly installed.
> 
> I did mention adding `manifest.json` in `next-pwa`'s Getting started section though!

Sorry for that,
I see it on the repo on Step 2.

But on the documentation itself it is place on below next9 version,
So Im guessing that on next 9 above there will be no need of manifest.json

**Comment by DuCanhGH** [comment]
@allestaire yeah that sounds like a weird confusion. It's nice that you have figured the issue out!

**Comment by allestaire** [comment]
Thank you for your fast response 😄
