### ISSUE TITLE
[Error -sw-entry.js:1 Uncaught ReferenceError: PWA_SW_ENTRY_WORKER is not defined]: 

### ISSUE THREAD

**Issue by aamaltf1** [DuCanhGH/next-pwa#33]
### Provide environment information

"next": "13.2.4",
"@ducanh2912/next-pwa": "^8.7.0",

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code help us address them faster

nextjs with appdir feature 

### To reproduce

- private repo

** next.config.js **

```js

const withPWA = require("@ducanh2912/next-pwa").default({
  dest: "public",
});
const withMDX = require('@next/mdx')({
  extension: /\.mdx?$/,
  options: {
    remarkPlugins: [],
    rehypePlugins: [],
 
  },
})

/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: false,
  pageExtensions: ['js', 'jsx', 'ts', 'tsx', 'mdx'],
  experimental: {
    appDir: true,
    serverComponentsExternalPackages: ["mongoose"],
  },
  webpack: (config, { isServer }) => {
    if (isServer) {
      // // Initialize the database connection
      // appConfiguration.initialize();
    }

    return config;
  },

}
module.exports = withPWA({
  ...nextConfig
});
```

### Describe the bug

```
sw-entry.js:1 Uncaught ReferenceError: __PWA_SW_ENTRY_WORKER__ is not defined
    at eval (webpack-internal:///(:3000/app-client)/./node_modules/@ducanh2912/next-pwa/dist/sw-entry.js:3:245)
    at (app-client)/./node_modules/@ducanh2912/next-pwa/dist/sw-entry.js (main-app.js:1079:1)
    at options.factory (webpack.js:722:31)
    at __webpack_require__ (webpack.js:37:33)
    at __webpack_exec__ (main-app.js:1096:61)
    at main-app.js:1097:37
    at webpackJsonpCallback (webpack.js:1394:39)
    at main-app.js:9:61
eval @ sw-entry.js:1
(app-client)/./node_modules/@ducanh2912/next-pwa/dist/sw-entry.js @ main-app.js:1079
options.factory @ webpack.js:722
__webpack_require__ @ webpack.js:37
__webpack_exec__ @ main-app.js:1096
(anonymous) @ main-app.js:1097
webpackJsonpCallback @ webpack.js:1394
(anonymous) @ main-app.js:9
```

**layout.tsx** 
```tsx
`"use client";
import "./globals.css";
import Script from "next/script";
import { useEffect, useState } from "react";


declare global {
  interface JQuery {
    slimScroll: any;
  }
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
   
  useEffect(() => {
    initGA();
    logPageView();
    
  });

  useEffect(() => {
    
    if("serviceWorker" in navigator) {
      window.addEventListener("load", function () {
       navigator.serviceWorker.register("/sw.js").then(
          function (registration) {
            console.log("Service Worker registration successful with scope: ", registration.scope);
          },
          function (err) {
            console.log("Service Worker registration failed: ", err);
          }
        );
      });
    }
  }, []);
  return (
    <html lang="en">
      <head>
        <title></title>
       
      
        <link crossOrigin='use-credentials' rel='manifest' href='/manifest.json' />
        <meta name="msapplication-TileColor" content="#da532c" />
        <meta name="theme-color" content="#ffffff" />
      </head>
      <body className="top-navigation">
        <div id="wrapper">
         
        </div>
      </body>
    </html>
  );
}
```

### Expected behavior

create a wpa

**Comment by DuCanhGH** [comment]
Please revert to 8.6.0 temporarily, I'll investigate as soon as possible.

**Comment by DuCanhGH** [comment]
`next-pwa` 8.7.1 has been released, please check if you still have this issue.

**Comment by roderickhsiao** [comment]
Thanks for the prompt fix!

**Comment by DuCanhGH** [comment]
@aamaltf1 also, just a note, the SW is automatically registered for you unless you explicitly disable that :) So you don't need that `useEffect`.

Also, why am I seeing JQuery definition 💀

**Comment by aamaltf1** [comment]
@DuCanhGH thank you very much for the quick response,
I updated the package the error is gone but still did not work.
the logs of pwa seems ok there is no sign of errors anywhere

`info  - (PWA) Compiling for server...
info  - (PWA) Compiling for client (static)...
info  - (PWA) Service worker: public\sw.js
info  - (PWA)   URL: /sw.js
info  - (PWA)   Scope: /
info  - (PWA) Building in development mode, caching and precaching are disabled for the most part. This means that offline support is disabled, but you can continue developing other functions in service worker.
info  - (PWA) Compiling for server...
event - compiled client and server successfully in 1788 ms (268 modules)
wait  - compiling...
wait  - compiling /page (client and server)...
event - compiled client and server successfully in 2.1s (514 modules)
Debugger attached.
Debugger attached.
wait  - compiling /_error (client and server)...
event - compiled client and server successfully in 1363 ms (515 modules)`
JQuery is a requirement where I work. 🤷

**Comment by DuCanhGH** [comment]
@aamaltf1 the log seems fine to me. Can you describe the issue further? Thanks!

**Comment by DuCanhGH** [comment]
@aamaltf1 hi, do you still have any issue with the package? If you don't, please close the issue. Thanks!

**Comment by DuCanhGH** [comment]
I am going to close the issue as it seems to have been finished. If you have any issue, feel free to re-open it or open a new one :)
