### ISSUE TITLE
[Bug - next-pwa]: On Vercel -  NOW_SANDBOX_WORKER_MAX_LAMBDA_SIZE: The Serverless Function "xx" exceeds the maximum size limit of 50mb.

### ISSUE THREAD

**Issue by boredland** [DuCanhGH/next-pwa#37]
### Provide environment information

next 13.4.6, next-pwa 8.7.1

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code help us address them faster

I could try, but I guess I would need to re-create a lot...

### To reproduce

As soon as I add this library, I am exceeding the size limits for serverless functions. For all serverless endpoints, the report vercel generates is quite similar to this:

![image](https://github.com/DuCanhGH/next-pwa/assets/4662748/feafab7c-381f-4ff9-addf-cee86f5c4e05)

### Describe the bug

The vercel build fails, because serverless functions grow to big.

### Expected behavior

Builds that don't increase in size?

### Additional information (if relevant)

Is this perhaps dueto @swc/core and swc-loader in the "dependencies" of the package?

**Comment by DuCanhGH** [comment]
That sounds problematic. Currently `@swc/core` and `swc-loader` is listed in `next-pwa`'s `"dependencies"` so that features that rely on `webpack` (such as `cacheOnFrontEndNav`, custom workers and offline fallbacks) work out of the box. Maybe we can reuse Next's webpack config instead.

For now perhaps you should not use the package while I work on that. Thanks!

**Comment by DuCanhGH** [comment]
@boredland `next-pwa` 9.0.0 has just been released. Please try it out to see if it works :)

From now on we will try to resolve `next/dist/build/swc` (Next's swc bindings) before `@swc/core`.

**Comment by DuCanhGH** [comment]
@boredland can you provide me a feedback? Thanks! Also, please close the issue if you've got it working :)

**Comment by boredland** [comment]
Hi there! Gave it a try, looks like it works pretty well. Thank you so much!

**Comment by DuCanhGH** [comment]
@boredland That's great!
