### ISSUE TITLE
[Bug - next-pwa]:  Offline fallback is not working with app directory

### ISSUE THREAD

**Issue by rahullilybltr** [DuCanhGH/next-pwa#40]
### Provide environment information

I have been trying to achieve it below way
```
const withPWA = require('@ducanh2912/next-pwa').default({
  dest: 'public',
  extendDefaultRuntimeCaching: false,
  cacheStartUrl: false,
  dynamicStartUrl: false,
  workboxOptions: {
    runtimeCaching: [...cachingArray],
  },
  fallbacks: {
    document: '/~offline',
  },
});
```

and created a folder in app directory app/~offline/page.tsx

page.tsx
```
import React from 'react';
export default async function Fallback() {
  return (
    <>
      <div>this is offline page</div>
    </>
  );
}

```

but this is not working with app directory but when i am tring to acheive it with pages/_offline it is working fine
when i am adding below into next-pwa properties then it turn out to be not working. Can we achieve it without caching the start url??
```
extendDefaultRuntimeCaching: false,
  cacheStartUrl: false,
  dynamicStartUrl: false,
  workboxOptions: {
    runtimeCaching: [...cachingArray],
  },
```

Next-pwa offline fallback not working in app directory as described here https://ducanh-next-pwa.vercel.app/docs/next-pwa/offline-fallbacks

**Comment by DuCanhGH** [comment]
I cannot reproduce the bug as described. `cacheStartUrl` and `dynamicStartUrl` are not related, maybe you can try removing `workboxOptions` and `extendDefaultRuntimeCaching` to see if it works? Thanks!

**Comment by rahullilybltr** [comment]
hey @DuCanhGH ,
It is working when i remove these properties.
```
extendDefaultRuntimeCaching: false,
  cacheStartUrl: false,
  dynamicStartUrl: false,
  workboxOptions: {
    runtimeCaching: [...cachingArray],
  },

```
but it is caching all the pages
Is there any way i can disable the `pages` caching.

Also, It is working fine on local but, when i am using your next-pwa, aws size limit exceeds because it is downloading a lot of dependencies. so my dependencies folders goes from 25mb (without next-pwa) to 150mb (next-pwa) with
