### ISSUE TITLE
[Bug - next-pwa]: "process is not defined" in custom worker

### ISSUE THREAD

**Issue by kodai3** [DuCanhGH/next-pwa#42]
### Provide environment information

```
"@ducanh2912/next-pwa": "latest",
"next": "13.4.4",
```

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code help us address them faster

https://custom-worker-gold.vercel.app

### To reproduce

1. Go to [custom-worker example](https://github.com/DuCanhGH/next-pwa/tree/master/examples/custom-worker).
2. Add script to use environmental variables in the worker/index.ts or its dependency
	```
       // shared/utils/index.ts
	   export function util(message: string) {
		  const nodeEnv = process.env.NODE_ENV;
		  console.log("nodeEnv", process.env.NODE_ENV);
		
		  console.log("Hello from util.");
		  console.log("es6+ syntax test:");
		  // eslint-disable-next-line prefer-const
		  let foo = { message: message };
		  console.log(foo?.message);
		}
    ```

### Describe the bug

It throw error `process is not defined`

### Expected behavior

no errors.

### Additional information (if relevant)

The usecase for me is I am trying to use [Firebase Cloud Messaging](https://firebase.google.com/docs/cloud-messaging/js/client) and I need to `initializeApp` with env vars.

**Comment by DuCanhGH** [comment]
I cannot reproduce as described, unfortunately.

This is the custom worker with the additional code `const nodeEnv = process.env.NODE_ENV; console.log("nodeEnv", process.env.NODE_ENV, nodeEnv);`:
```js
(()=>{"use strict";!function(e){console.log("nodeEnv","production","production"),console.log("Hello from util."),console.log("es6+ syntax test:");let o=e;console.log(o)}("working"),self.addEventListener("message",(e=>{console.log(e?.data)})),self.addEventListener("push",(e=>{const o=JSON.parse(e?.data?.text()||"{}");e?.waitUntil(self.registration.showNotification(o.title,{body:o.message,icon:"/icons/android-chrome-192x192.png"}))})),self.addEventListener("notificationclick",(e=>{e?.notification.close(),e?.waitUntil(self.clients.matchAll({type:"window",includeUncontrolled:!0}).then((function(e){if(e.length>0){let o=e[0];for(let t=0;t<e.length;t++)e[t].focused&&(o=e[t]);return o.focus()}return self.clients.openWindow("/")})))}))})();
```
You can see that it has `console.log("nodeEnv","production","production")`, which means that `process.env.NODE_ENV` was correctly replaced. Perhaps you are using environment variables different from `NODE_ENV`, which I might need to investigate further later (working on a new Next.js PR right now...).

**Comment by kodai3** [comment]
Thank you for the quick response.

It was custom environment variables. sorry for the confusion
![image](https://github.com/DuCanhGH/next-pwa/assets/33568829/d4b4ecdf-dbdf-4168-88be-32093cb83fb7)

> (working on a new Next.js PR right now...)

No worries. Thank you for your work. it saves my day.

**Comment by DuCanhGH** [comment]
@kodai3 I just noticed that we already inherits `webpack.DefinePlugin`, so what you need to do is just prefixing your environment variables with `NEXT_PUBLIC_`...

**Comment by kodai3** [comment]
@DuCanhGH 

Thank you for confirming.

Weird thing is I have these env variables and with `next-pwa` in the `public/worker-*.js` `NEXT_PUBLIC_` all converted exept `NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID`.
![image](https://github.com/DuCanhGH/next-pwa/assets/33568829/628c79f8-2525-4e3e-a200-7ede705d4aad)

![スクリーンショット 2023-06-28 0 58 33](https://github.com/DuCanhGH/next-pwa/assets/33568829/f1f098c3-20b9-4edf-8ae8-4ded3261dce9)

It's my production code so I can't share, but Do you have any clue what cloud be the cause ?
I'll try to repro repo, if needed.

**Comment by DuCanhGH** [comment]
@kodai3 your `.env` may have a surprise or two, perhaps you should recheck it? Thanks!

**Comment by kodai3** [comment]
No env change, cache delete and rebuild seems to did the trick.
