### ISSUE TITLE
[Bug - next-pwa]: 

### ISSUE THREAD

**Issue by FilipChalupa** [DuCanhGH/next-pwa#46]
### Provide environment information

`next@13.4.5`
`@ducanh2912/next-pwa@9.1.1` (@ducanh2912/next-pwa@9.0.0 was ok)

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code help us address them faster

-

### To reproduce

Run next build.

### Describe the bug

`Cannot find module '@swc/core'`

### Expected behavior

Build without error.

### Screenshots (if relevant)

![image](https://github.com/DuCanhGH/next-pwa/assets/1045362/effe5a07-80dc-41f5-8ea5-5db5ccf7f8a4)

**Comment by DuCanhGH** [comment]
Oops. I will work on a fix soon!

**Comment by jl75** [comment]
Thanks for your great work @DuCanhGH!
9.0.1 is the last working version (9.1.0 is also broken).

**Comment by FilipChalupa** [comment]
Works nicely. Thank you.

**Comment by DuCanhGH** [comment]
@rollingmoai can you open a new issue with a reproduction? Thanks!

**Comment by DuCanhGH** [comment]
@rollingmoai I just released `next-pwa` 9.1.4, please let me know if it is working :)
