### ISSUE TITLE
[Bug - next-pwa]: how to test offline fallback feature

### ISSUE THREAD

**Issue by aNyMoRe0505** [DuCanhGH/next-pwa#51]
### Provide environment information

same version as this [example](https://github.com/DuCanhGH/next-pwa/tree/master/examples/offline-fallback-v2)

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code help us address them faster

https://github.com/DuCanhGH/next-pwa/tree/master/examples/offline-fallback-v2

### To reproduce

Hello, thank you for forking this project, it help me a lot

 I want to test offline fallback feature as described [here](https://github.com/DuCanhGH/next-pwa/tree/master/examples/offline-fallback-v2)

After running local server, open browser go to localhost:3000

the site work properly and I let my network offline, reload the page

the site still work properly (this is expected, since the route has been cached)

my question is how to let the site fallback to /_offline when network offline

I guess I need to use `buildExcludes` option to achieve, but I am not sure what files I can exclude

in my project, I don't want to use pre-cache feature, so my buildExcludes config is `buildExcludes: [() => true]`

but for the offline fallback feature work, I think I need to include the fallback page files.

thank you !

### Describe the bug

as described above

### Expected behavior

as described above

**Comment by DuCanhGH** [comment]
Workbox needs to precache those pages for this feature to work. If you exclude everything from precaching, it is not guaranteed that your fallback page would work. Perhaps you should opt certain assets out of precaching instead. But if you are absolutely certain, maybe you can try this:
```js
const withPWA = require("@ducanh2912/next-pwa").default({
  buildExcludes: [({ asset }) => !/(.*)\/~offline(.*)/.test(asset.name)],
  fallbacks: {
    document: "/~offline",
  },
});
```
I'm not sure if it works, but yeah.

**Comment by aNyMoRe0505** [comment]
@DuCanhGH 
After testing, it still doesn't work
I guess I need to pre-cache first load JS shared by all
<img width="414" alt="截圖 2023-07-12 10 22 35" src="https://github.com/DuCanhGH/next-pwa/assets/9814815/5b6e3add-ccfd-4c57-9cbc-2d290ffe8d1d">
I will continue testing when I have free time.
Thank you for your response

**Comment by DuCanhGH** [comment]
@aNyMoRe0505 you need to precache those assets for your offline fallback page to work, but I don't really see it being so related. You would also need to precache `/~offline`'s `.js` files as well, so I suggest precaching every asset starting with `/_next/static/chunks` using `buildExcludes: [({ asset }) => !/\/_next\/static\/chunks\/(.*).js/.test(asset.name)]`. Maybe try doing that to see if it works? Thanks!

Oh and sorry for the late reply, I've been quite busy lately :)

**Comment by aNyMoRe0505** [comment]
@DuCanhGH 
Thank you for your response !
everyone has a lot of work to do, so don't worry about it
I have other things to handle at the moment, but I will reply after I have some free time to test. Thank you.

**Comment by aNyMoRe0505** [comment]
@DuCanhGH 
I just found that we still can use `buildExcludes: [() => true]`
the key is if we want to test offline fallback, we need to use next product build (since dev build is on-demand)
and we need to set `cacheStartUrl` & `dynamicStartUrl` to false
if we cache start url, when user offline, the start url in cache so we will not be redirected to offline page

the following is the final config I use

```js
const withPWA = require("@ducanh2912/next-pwa").default({
  dest: "public",
  disable: false,
  buildExcludes: [() => true],
  cacheStartUrl: false,
  dynamicStartUrl: false,
});
```

Thanks for your help ! I think we can close this issue now

**Comment by DuCanhGH** [comment]
@aNyMoRe0505 alright, let's close it :)
