### ISSUE TITLE
Error: Cannot find module 'webpack'

### ISSUE THREAD

**Issue by rohankm** [DuCanhGH/next-pwa#52]
Hi,
I tried using with   `"next": "13.4.9"`

im getting the following error 

`
Error: Cannot find module 'webpack'
`

**Comment by SuttonJack** [comment]
Encountering the same. Started happening after a recent next.js version bump. Adding `webpack` as a dependency to my project resolved it though


<img width="500" alt="Screenshot 2023-07-10 at 11 01 37 AM" src="https://github.com/DuCanhGH/next-pwa/assets/92991945/f7222843-66f1-4b20-ab25-a52521511207">

**Comment by DuCanhGH** [comment]
`webpack` was listed in `next-pwa`'s `dependencies`, perhaps your package manager didn't warn you about that.

It no longer is in 9.2.0 though, as we now reuse Next's `webpack` instance :)

**Comment by rohankm** [comment]
> `webpack` was listed in `next-pwa`'s `dependencies`, perhaps your package manager didn't warn you about that.
> 
> It no longer is in 9.2.0 though, as we now reuse Next's `webpack` instance :)

But I still have the error which is solved after `yarn add webpack`

**Comment by DuCanhGH** [comment]
@rohankm I cannot reproduce the issue as described. Perhaps you will need to provide a reproduction.
One thing though, I saw this when trying to install the package using yarn:
```
warning "@ducanh2912/next-pwa > clean-webpack-plugin@4.0.0" has unmet peer dependency "webpack@>=4.0.0 <6.0.0".
warning "@ducanh2912/next-pwa > workbox-webpack-plugin@7.0.0" has unmet peer dependency "webpack@^4.4.0 || ^5.9.0".
warning "@ducanh2912/next-pwa > terser-webpack-plugin@5.3.9" has unmet peer dependency "webpack@^5.1.0".
```
yarn did warn you about peer dependencies missing, but maybe you didn't notice :)
