### ISSUE TITLE
[Feature request]: Set a configurable prefix path for the custom worker.

### ISSUE THREAD

**Issue by danielpasch** [DuCanhGH/next-pwa#60]
### Which project is this feature idea for?

@ducanh2912/next-pwa

### Describe the feature you'd like to request

We would like to adjust the `custom worker` path, so that the `custom worker` file is not part of the public root. This is important to us because of root caching assets handling. Currently we can only configure a custom worker, which will bundled as hashed `worker-*js` to the static folder. It would be helpful to shift this custom worker file out of root by setting a `prefix` in the path.

### Describe the solution you'd like

Example:

We would like to host the `custom worker` file like this...
```
example.com/some/other/asset/path/worker-*.js
```
instead of this...
```
example.com/worker-*.js
```

### Describe alternatives you've considered

-

**Comment by danielpasch** [comment]
What do you mean, is it also possible to remove the hash from `worker-<hash>.js` (maybe by config). Right now, the logic uses the `BUILD_ID` on every new build, whether something has changed in worker or not. I think it's probably obsolete, as the service-worker will check on every update byte-by-byte if there is a change. https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerRegistration/update

**Comment by DuCanhGH** [comment]
@danielpasch I don't really understand this question to be honest. But if I've got it right, this is how you can remove the hash: 
```js
const nextConfig = {
  generateBuildId() { return ""; },
};

export default withPWA(nextConfig);
```
To be honest though, while it is probable that the service worker does check if its imported scripts have changed; if the custom worker is cached by the CDN and the service worker just somehow gets an outdated version, it might cause problems for your users. I don't see it hashing the custom worker's filename making such an impact though, as the filename only changes when you rebuild your app, and it ensures that there's no chance of getting an outdated version. 

It also doesn't look anything near being obsolete to me to be honest, if you look into `.next/static/chunks`, you can see that all the scripts look something like this: `{scriptName}-{crazyHash}.js`.

**Comment by danielpasch** [comment]
@DuCanhGH i think the difference between the `BUILD_ID` and the `crazyHashes` inside the `.next/static/chunks` is the way it is created. The `BUILD_ID` will be change on every prod build, while the `crazyHashes` are created and builded by webpack, which also check the file byte by byte, and generate another hash if the file has changed. 

The `worker-*.js` hash will change all the time, as it's not "webpack bundled", but static set with `BUILD_ID` (see https://github.com/DuCanhGH/next-pwa/blob/197ff05841149eedce1957d222eea08bcd328693/packages/next-pwa/src/webpack-builders/build-custom-worker.ts#L44)

I mean it's just a question, if it's possible to also make this configurable. The main request to create a prefix path is more important to me, than this one.

**Comment by DuCanhGH** [comment]
@danielpasch ah yes, if that's the case then I will consider adding an option to allow using Webpack's hashing instead of `buildId`, if we can get the actual filename after bundling the custom worker.

Regarding adding a `basePath`-like option for the custom worker, if I'm done with my other work then I'll work on that should it be reasonable enough :)

**Comment by DuCanhGH** [comment]
@danielpasch I've decided against using webpack's hashing, as it requires us to finish building everything (custom worker, fallback worker,...) before letting Next.js do its things. And it also breaks development mode (`webpack.DefinePlugin` is not called early enough...).

I'm considering using our `getRevision` function instead, which hashes the file using `node:crypto` into a string.

**Comment by danielpasch** [comment]
Sounds good. Thanks for acting quickly.

**Comment by DuCanhGH** [comment]
@danielpasch so the final design is that you get an option just like `sw`, and you can do something like: `withPWA({ customWorkerPrefix: "foo/bar/worker" });`, which will change the custom worker's output to `{dest}/foo/bar/worker-{hash}.js`. Note that `customWorkerDest` doesn't have the same effect, in that it only changes the output directory and not the URL, so you have to rewrite `/worker-{hash}.js` to `/foo/bar/worker-{hash}.js`.
