### ISSUE TITLE
[Feature request]: I'd like to support your work

### ISSUE THREAD

**Issue by elsigh** [DuCanhGH/next-pwa#65]
### Which project is this feature idea for?

@ducanh2912/next-pwa

### Describe the feature you'd like to request

As https://github.com/sponsors isn't avail in Vietnam is there another way to support your work?

### Describe the solution you'd like

Take my money

### Describe alternatives you've considered

Trying to find you in Discord, can't DM in Twitter, etc. ;)

**Comment by DuCanhGH** [comment]
Quoting my own response in #29:

> I don't really like the idea. I forked next-pwa to allow the community to continue creating PWAs with Next.js easily and securely - and I don't plan to make money from it. I'd love it if you can use the money to help those in need instead. [The core-js guy](https://github.com/zloirock/core-js/blob/master/docs/2023-02-14-so-whats-next.md), perhaps? I hope that this doesn't come off as being rude.
> 
> Thanks for the support!

It's not like I actually have a way to receive such form of support at the moment though :) Thank you, nonetheless.

**Comment by elsigh** [comment]
Absolutely not rude! I try to support authors and projects I use, so I'll take your suggestion and send support to them as I would to you. :)
