### ISSUE TITLE
[Feature request]: CACHE ALL PAGES ON BUILD

### ISSUE THREAD

**Issue by Wilfried02** [DuCanhGH/next-pwa#67]
### Which project is this feature idea for?

@ducanh2912/next-pwa

### Describe the feature you'd like to request

I would like all my pages to be added to the manifest in order to be cached when the service worker is activated

### Describe the solution you'd like

Add ability to modify manifest entries to be cached

### Describe alternatives you've considered

I don't see any other possibility

**Comment by DuCanhGH** [comment]
Yeah I don't think there's really a way either. You'd need something like a pages manifest to determine which pages to cache, but where can we even get something like that? Either way, I think letting the service worker cache pages as they are requested is better, as we can avoid making a large number of network requests (which can really affect your users) on the service worker's activation.

**Comment by Wilfried02** [comment]
ok
