### ISSUE TITLE
[Bug - next-pwa]: workbox cache invalidation

### ISSUE THREAD

**Issue by AdisonCavani** [DuCanhGH/next-pwa#69]
### Provide environment information

```
"@ducanh2912/next-pwa": "^9.4.0"
"next": "^13.4.12"
```

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code help us address them faster

https://github.com/AdisonCavani/todo-list/tree/master/frontend

### To reproduce

`next.config.js`
```js
const withPWA = require("@ducanh2912/next-pwa").default({
  dest: "public",
  disable: process.env.NODE_ENV !== "production",
});

/** @type {import('next').NextConfig} */
const nextConfig = {
  // Other settings...

  headers() {
    return [
      {
        source: "/(.*)",
        headers: securityHeaders,
      },
    ];
  },
};

// https://nextjs.org/docs/app/api-reference/next-config-js/headers#content-security-policy
const ContentSecurityPolicy = `
  default-src 'self';
  script-src 'self' 'unsafe-eval' 'unsafe-inline' https://insights.k1ng.dev;
  style-src 'self' 'unsafe-inline';
  font-src 'self';
  img-src 'self' data: https://avatars.githubusercontent.com https://*.googleusercontent.com;
  connect-src 'self' https://insights.k1ng.dev;
`;

const securityHeaders = [
  // https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP
  {
    key: "Content-Security-Policy",
    value: ContentSecurityPolicy.replace(/\s{2,}/g, " ").trim(),
  },
  // https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy
  {
    key: "Referrer-Policy",
    value: "origin-when-cross-origin",
  },
  // https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options
  {
    key: "X-Frame-Options",
    value: "DENY",
  },
  // https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Content-Type-Options
  {
    key: "X-Content-Type-Options",
    value: "nosniff",
  },
  // https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-DNS-Prefetch-Control
  {
    key: "X-DNS-Prefetch-Control",
    value: "on",
  },
  // https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security
  {
    key: "Strict-Transport-Security",
    value: "max-age=31536000; includeSubDomains; preload",
  },
  // https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy
  {
    key: "Permissions-Policy",
    value: "camera=(), microphone=(), geolocation=()",
  },
];

module.exports = withPWA(nextConfig);
```

### Describe the bug

The workbox cache is not invalidated and it's persisted even on new production build (I'm using Vercel to deploy).
This causes issues when you update the `Content Security Headers` - the old one are cached and they do not allow to connect to the new "content".

When I do a hard refresh end empty cache, the errors are cleared, but when I refresh the page, they are still popping out. I cannot clear the cache.

I also tried to clear cache and unregister the service worker, but the issue still occurs.

### Expected behavior

The `Content Security Headers` should be invalidated on new builds.

### Screenshots (if relevant)

![Dev console errors](https://github.com/DuCanhGH/next-pwa/assets/76855180/cb9b6f4f-8880-45b4-8503-3a9c7a8e0cc0)
![Clearing cache](https://github.com/DuCanhGH/next-pwa/assets/76855180/384e2d99-eb55-4387-a675-24a595ebf8f6)

**Comment by DuCanhGH** [comment]
Can you try something like this?
```ts
// worker/index.ts
self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((cacheKeys) =>
        Promise.all(cacheKeys.map((key) => caches.delete(key)))
      )
  );
});
```
Not sure if that'll work, but it will delete all the caches in Cache Storage on the service worker's activation. Hope this helps!

**Comment by AdisonCavani** [comment]
Where I should put this code?
I don't have any `worker/index.ts` file in my configuration.

**Comment by DuCanhGH** [comment]
@AdisonCavani see https://ducanh-next-pwa.vercel.app/docs/next-pwa/custom-worker
Just create a new `worker/index.ts` (or `.js` if you use JS), relative to your project directory.

**Comment by AdisonCavani** [comment]
I added a `worker/index.ts` and `webworker` to `compilerOptions.lib` in `tsconfig.json`, but I'm getting this error:

```
- error (pwa) Failed to compile the custom worker.
- error (pwa) asset worker-development.js 1.49 KiB [emitted] [compared for emit] (name: main)
./worker/index.ts 39 bytes [built] [code generated] [1 error]

ERROR in ./worker/index.ts
Module build failed (from ./node_modules/.pnpm/@ducanh2912+next-pwa@9.7.0_@swc+core@1.3.86_esbuild@0.18.20_next@13.4.19_webpack@5.88.2/node_modules/@ducanh2912/next-pwa/dist/swc-loader.cjs): 
Error: unknown field `lazy`, expected `resolveFully` at line 1 column 689

webpack 5.86.0 compiled with 1 error in 687 ms
```

**Comment by AdisonCavani** [comment]
```ts
declare const self: ServiceWorkerGlobalScope;

self.addEventListener("activate", (event) => {
  console.log("activated");

  event.waitUntil(
    caches.keys().then((cacheKeys) => {
      Promise.all(cacheKeys.map((key) => caches.delete(key)));
      console.log("removed");
    }),
  );
});
```

![image](https://github.com/DuCanhGH/next-pwa/assets/76855180/eebb76a6-3f5c-4095-bf0b-973fd246293d)

Unfortunately this does not resolve the issue.

**Comment by DuCanhGH** [comment]
@AdisonCavani that `connect-src` doesn't even specify `https://avatars.githubusercontent.com` so how is it supposed to get through? 💀

**Comment by AdisonCavani** [comment]
> @AdisonCavani that `connect-src` doesn't even specify `https://avatars.githubusercontent.com` so how is it supposed to get through? 💀

https://github.com/AdisonCavani/todo-list/blob/master/src/next.config.js#L51

I removed the next-pwa. Unregistered the service worker and added it back again. Now it works fine.

**Comment by DuCanhGH** [comment]
@AdisonCavani seems that you have fixed the issue :) I'd say that CSP is pretty hard with Next.js, to be honest. I'd read the console more carefully if this were to happen to me, though.

**Comment by AdisonCavani** [comment]
The `https://avatars.githubusercontent.com` was only used as a Image src, so it was present only in `img-src`. It seems that `workbox` changes someting and it needed to be in `connect-src` also.

**Comment by DuCanhGH** [comment]
@AdisonCavani Workbox uses `fetch()` (which is restricted by `connect-src`, mind you) in the service worker, so it's no wonders, really. I understand the confusion, but if you work with service workers you will notice `fetch()`, `caches`, `Request`, `Response`,... a lot.

> I honestly don't think the PWA is going to be popular. There are a lot of issues.

Well, this topic is not something I'd like to discuss too much. It is, at the end of the day, subjective. I personally think that PWAs won't replace native apps, neither will it become so popular that everyone has to adopt it, but the former is a good alternative to the latter, especially when you don't want to waste too much effort and money on developing the same thing multiple times in parallel.

> For example in Firefox (android) the PWA app launches in "gray screen" a lot.

Firefox's support of PWAs are somewhat problematic to be honest, despite being the first to adopt it (afaik). That I can't use PWAs with Firefox without some 3rd party extension is annoying. I still love the browser though, with it being my main daily driver.
Other browsers shouldn't really have this issue if you configure your PWA correctly.
