### ISSUE TITLE
[Bug - next-pwa]: FetchEvent.respondWith received an error

### ISSUE THREAD

**Issue by aaronabf** [DuCanhGH/next-pwa#79]
### Provide environment information

```
next - 13.4.19
@ducanh2912/next-pwa - 9.5.0
```

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code help us address them faster

n/a

### To reproduce

We are unable to successful reproduce the issue.

### Describe the bug

We run this fork of next-pwa and are having users sporadically seeing this error message in Safari:
```
Safari can't open the page.
The error was: "FetchEvent.respondWith received an error: no-response: no-response :: ["url":"https://our-homepage-here"}]"
```
My best guess is it's an issue with this [code block here](https://github.com/DuCanhGH/next-pwa/blob/edac6066df64887640ee75e6269879e342c7c40e/packages/next-sw/src/build/generate-sw/base-sw-utils.ts#L27-L38), but I do not know this codebase very well.

### Expected behavior

For this error to not surface.

### Screenshots (if relevant)

![original-E50BE68B-8570-4F38-8D13-F3C172ED0F6D](https://github.com/DuCanhGH/next-pwa/assets/4202147/c8077063-e9ed-4e73-adaf-1161657fd70f)

_No response_

**Comment by DuCanhGH** [comment]
`packages/next-sw` is not what you are currently using as it is a work-in-progress at the moment. It is actually `packages/next-pwa`. Sounds like a weird issue, will investigate when I'm free :)

**Comment by aaronabf** [comment]
> `packages/next-sw` is not what you are currently using as it is a work-in-progress at the moment. It is actually `packages/next-pwa`. Sounds like a weird issue, will investigate when I'm free :)

I see! Thanks for the quick reply.

There is this [Stackoverflow post](https://stackoverflow.com/questions/75443305/pwanext-jsios-i-sometimes-cannot-get-data-from-server-the-error-message-i?noredirect=1&lq=1):

> My PWA app sometimes cannot get data from server. It shows errors like:
> FetchEvent.respondWith received an error: no-response: no-response Fetch API cannot load no internet connection
> But if we reload the page, it could get data normally. And these bugs only happened in Safari. It is working well in Chrome or window devices.

This seems to align with what we are seeing as well, as only uses in Safari have reported issue and this the sporadic nature can be explained by a spotted connection. This might just be a Safari bug but I wonder if there is some way to more gracefully avoid this failure.

**Comment by DuCanhGH** [comment]
@aaronabf went through the repo and yeah, maybe it's due to a slow internet connection. I honestly don't know why this is happening and how to fix it either. Seems like a Workbox or Safari issue because I've not found anything in the repo that could be causing this :( Maybe some help on reproducing would do the trick.

**Comment by pz129** [comment]
@DuCanhGH It seems to go away whenever you clear the browser cache. Once someone hits it, they will consistently have the issue until the cache is cleared.

**Comment by pz129** [comment]
@DuCanhGH any updates as to why this might be happening? it's not a good UX to tell users to clear their cache when this happens. Ideally it goes away without having to clear the cache.

**Comment by DuCanhGH** [comment]
@pz129 I haven't a clue either. This can't really be reliably reproduced, so there's that.

**Comment by DuCanhGH** [comment]
@aaronabf can I have your `withPWA` config and `sw.js`? I'd like to inspect the service worker to see if there's some weird stuff there.

**Comment by aaronabf** [comment]
Huh that's really odd.

Our configuration is fairly minimal:
```
const withPWA = require("@ducanh2912/next-pwa").default({
  dest: "public",
  register: true,
  skipWaiting: true
})
```
And the `sw.js` can be found here: https://www.passes.com/sw.js

**Comment by DuCanhGH** [comment]
![IMG_5816](https://github.com/DuCanhGH/next-pwa/assets/75556609/20d73a02-f772-4004-b01c-b3a7cc5c9f2c)
Just got this problem on my device today 😂 Took months to actually get it once. I'm guessing that this happens because there's no cached page to serve. Can you try using offline fallbacks to see if that helps?

**Comment by FixDev** [comment]
Any update for this issue?

**Comment by DuCanhGH** [comment]
@FixDev this can happen [when a Workbox strategy fails to find a response](https://github.com/GoogleChrome/workbox/blob/604ff0ccb9db96c0defd6d285d645d283536092e/packages/workbox-strategies/src/NetworkFirst.ts#L146-L149), which means that both the cache and the network couldn't provide a valid response. To fix this, try using fallbacks or `handlerDidError` or precaching the URLs.
