### ISSUE TITLE
[Bug - next-pwa]: waiting event not fired/handled for PWA

### ISSUE THREAD

**Issue by mkelley33** [DuCanhGH/next-pwa#81]
### Provide environment information

This problem occurs in the code based on the following example:

https://github.com/DuCanhGH/next-pwa/blob/master/examples/lifecycle/pages/index.tsx

```
 wb.addEventListener('waiting', () => {
        // `event.wasWaitingBeforeRegister` will be false if this is the first time the updated service worker is waiting.
        // When `event.wasWaitingBeforeRegister` is true, a previously updated service worker is still waiting.
        // You may want to customize the UI prompt accordingly.
        // https://developer.chrome.com/docs/workbox/handling-service-worker-updates/#the-code-to-put-in-your-page
        if (
          confirm(
            'A newer version of this web app is available, reload to update?'
          )
        ) {
          wb.addEventListener('controlling', () => {
            window.location.reload();
          });

          // Send a message to the waiting service worker, instructing it to activate.
          wb.messageSkipWaiting();
       }
```

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code help us address them faster

https://github.com/mkelley33/mkelley33-pwa/blob/main/src/components/RefreshPwaProvider.tsx

### To reproduce

Using "next": "13.4.19" and "@ducanh2912/next-pwa": "^9.5.0" delete any `.next` directory in the project, run `npm run build` and `npm run start`.  Install the PWA.  Unregister the service worker, and repeat the previous steps.  Note: no confirmation window is displayed asking user if they would like to install the latest version of the PWA.

### Describe the bug

When a new version of the PWA has been created, the user isn't prompted to install it given the code listed in the github link I provided.

### Expected behavior

The user should be presented with a confirmation dialog to install the latest version of the PWA.

**Comment by DuCanhGH** [comment]
I mean, if you unregister the service worker then the new service worker won't wait to take control of the page, right? If that's the case, the `"waiting"` event shouldn't be fired.
If you don't unregister it though, seems that the example is working as expected.

**Comment by mkelley33** [comment]
@DuCanhGH Not under the new app router.  It's not working for me.  I never get a confirm dialog for a new build.

**Comment by DuCanhGH** [comment]
@mkelley33 weird, `examples/lifecycle` seems to be working with App Router for me. Are you sure that the service worker is properly installed? I mean, seems that `navigator.serviceWorker` is not available in private mode. Also, check if moving `wb.messageSkipWaiting()` above `wb.addEventListener('controlling', () => { /*...*/ }` works. Thanks!

**Comment by mkelley33** [comment]
@DuCanhGH so, I tried moving `wb.messageSkipWaiting()` as you recommended, but I still didn't get a confirm dialog after making some changes to the app, removing the `.next` directory, then running `npm run build` and `npm run start`, and visiting the home page again.  The updates to the app however did appear in the browser, so maybe it doesn't need to prompt the user with a confirmation dialog?  In any case, the `waiting` event handler is never run for me.  Do you get a prompt in Chrome?

**Comment by DuCanhGH** [comment]
@mkelley33 I get a prompt on both Chromium and Firefox. Can you check if `deps-2:examples/lifecycle` works for you?

**Comment by mkelley33** [comment]
@DuCanhGH I get the prompt immediately in Chrome after trying `deps-2:example/lifecycle`.  So, I guess it works under the pages directory, but not under the new app directory convention in a client component as I've done in [https://github.com/mkelley33/mkelley33-pwa/blob/main/src/components/RefreshPwaProvider.tsx](https://github.com/mkelley33/mkelley33-pwa/blob/main/src/components/RefreshPwaProvider.tsx).  Can you think of what might be preventing the correct behavior from occurring in my application?

**Comment by mkelley33** [comment]
@DuCanhGH I should note that the other events fire and are handled such as `activated`, `controlling`, and `installed`.

**Comment by DuCanhGH** [comment]
@mkelley33 I updated `deps-2:example/lifecycle` to make use of App Router. If you visit `/` and it is working, surely that means it is working right?

**Comment by mkelley33** [comment]
@DuCanhGH Not in my repo, which is using app router under the `app` directory and not the `pages` directory.  The content does, however, seem to refresh without any prompt to reload the app.  If you try cloning my repo, installing it, building it, and running it does it prompt you to update on subsequent builds?  Unless you think I'm not getting the expected behavior, I think you can close this bug as my content appears to update without any prompting.

**Comment by mkelley33** [comment]
@DuCanhGH that fixed it! I was following the example at [https://ducanh-next-pwa.vercel.app/docs/next-pwa/getting-started](https://ducanh-next-pwa.vercel.app/docs/next-pwa/getting-started) under the `next.config.mjs` tab.  It would seem that the docs example on the website doesn't work.  It would be nice if somehow we could use the `.mjs` file. Perhaps, you could update this as a future improvement?  Thank you for all of your help!  I'm closing this out since it's not really a bug so much as a matter of preference that doesn't seem to be working yet.

**Comment by DuCanhGH** [comment]
@mkelley33 the code included in the docs is only basic enough to get the app going, and you need to follow the examples
to the letter or clone it using `npm create next-app`, then maybe customize it later, for example changing it so that `nextConfig` is wrapped with `withPWA` only in certain phases like in the docs:
```js
const nextConfigFunction = async (phase) => {
  if (phase === PHASE_DEVELOPMENT_SERVER || phase === PHASE_PRODUCTION_BUILD) {
    const withPWA = (await import("@ducanh2912/next-pwa")).default({
      dest: "public",
      // other settings, such as register, workboxOptions
    });
    return withPWA(nextConfig);
  }
  return nextConfig;
};
```

**Comment by mkelley33** [comment]
@DuCanhGH I appreciate the clarification.  Thanks for all the help!
