### ISSUE TITLE
[Bug - next-pwa]: offline fallback not working

### ISSUE THREAD

**Issue by skiddolo** [DuCanhGH/next-pwa#82]
### Provide environment information

- next 13.0.3
@ducanh2912/next-pwa 9.5.0

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code help us address them faster

only local

### To reproduce

- yarn create next-app --example https://github.com/DuCanhGH/next-pwa/tree/master/examples/offline-fallback-v2 offline-fallback-app

- cd offline-fallback-app
- npm run build
- npm run dev

### Describe the bug

hi,
i tried the "offline-fallback-v2" like the example but there's no redirection to the offline page also after a reload

### Expected behavior

showing the offline page

**Comment by renzo4web** [comment]
Hello I have the same problem

this is my `next.config.js`

```
const withPWA = require("@ducanh2912/next-pwa").default({
  dest: "public",
  cacheOnFrontEndNav: true,
  aggressiveFrontEndNavCaching: true,
});

/** @type {import("next").NextConfig} */
const nextConfig = {
  reactStrictMode: true,
};

module.exports = withPWA(nextConfig);
```

**Comment by DuCanhGH** [comment]
I cannot reproduce this issue.
![image](https://github.com/DuCanhGH/next-pwa/assets/75556609/69212561-b492-40dc-8378-36c2945a9984)
![image](https://github.com/DuCanhGH/next-pwa/assets/75556609/2b9d6bbc-1921-47f7-befb-fc0e6f867911)

**Comment by raihan-suryanom** [comment]
Uhm any updates I guess?

**Comment by DuCanhGH** [comment]
@skiddolo @renzo4web @raihan-suryanom I just... realized what went wrong. Unbelievably wrong. Basically, after we build the workers, `next-pwa`'s `importScripts` is not passed to Workbox. What in the world.

Seriously sorry about this! Not sure why I couldn't reproduce this issue though.
