### ISSUE TITLE
[Bug - next-pwa]: cant build

### ISSUE THREAD

**Issue by joacub** [DuCanhGH/next-pwa#83]
### Provide environment information

"next": "13.4.20-canary.32" cant build

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code help us address them faster

no response

### To reproduce

"next": "13.4.20-canary.32"

### Describe the bug

cant build

### Expected behavior

Build successfully

### Screenshots (if relevant)

<img width="1113" alt="image" src="https://github.com/DuCanhGH/next-pwa/assets/2091228/c804e185-f7ed-4a8e-980b-4e8d9ffd238f">

**Comment by DuCanhGH** [comment]
Yeah, seems like recent `swc` versions are bugged. You may want to override the `swc` that we use in `next-pwa` by installing `@swc/core@1.3.78` for now.

**Comment by joacub** [comment]
> Yeah, seems like recent `swc` versions are bugged. You may want to override the `swc` that we use in `next-pwa` by installing `@swc/core@1.3.78` for now.

Tank you so much, that works.

**Comment by DuCanhGH** [comment]
Seems that removing `module.lazy` and `module.importInterop` from `swcConfig` works. Not sure why though, seems like a bug (the types seem to indicate that these options are not removed).

**Comment by VVIERV00** [comment]
I encountered an issue with swc and next-pwa. The error was:
`Module build failed (from ./node_modules/@ducanh2912/next-pwa/dist/swc-loader.cjs):`

I temporarily resolved it by commenting out the following configuration:
`//dest: "public",
  //cacheOnFrontEndNav: true,
  //aggressiveFrontEndNavCaching: true,`

**Comment by DuCanhGH** [comment]
I created issue https://github.com/swc-project/swc/issues/7979, please continue the discussion there if needed.
@VVIERV00 I mentioned a workaround right above, so you don't need to opt out of those features.
