### ISSUE TITLE
dynamicStartUrl Not Working As Expected on Mobile 

### ISSUE THREAD

**Issue by terencehf** [DuCanhGH/next-pwa#87]
### Provide environment information

    "next": "13.4.12",    "@ducanh2912/next-pwa": "^9.5.0",

### Whose documentation is this feedback for?

@ducanh2912/next-pwa

### Describe the problem

this is my current config for the pwa I'm trying to create.

```js
const withPWA = require("@ducanh2912/next-pwa").default({
  disable: false,
  dest: "public",
  cacheOnFrontEndNav: false,
  cacheStartUrl: true,
  dynamicStartUrl: true,
  workboxOptions: {
    skipWaiting: true,
  },
});
```

My startUrl or "/" is an async server component where I make a fetch to see whether a user exists based on a token (retrieved using cookies from "next/headers") and if they do then I render UserComponent or else I render a vanilla home page.

When I visit the page on the website, when I install the pwa on my computer it works as expected, by which I mean the page is dynamically rendered based on the data retrieved by the fetch call on the server before page load.

However, when I install the pwa on an android device , the first time the pwa loads, I get the vanilla home page, despite me manually knowing a token is present. If I pull to refresh the screen, it updates to the correct UserComponent view.

I have tried to the setting cacheStartUrl to false in the config as well and got the same result. 

Any advice on how I can fix this or what I'm doing wrong?

### Expected behavior

when the pwa is installed on mobile, the startUrl which is an async server component should dynamically render UI based on state returned by a fetch call on load.

### Additional information (if relevant)

Turning the startUrl into a client component and running the fetch in a useEffect does work. However I'd prefer to not do that, if possible.

**Comment by DuCanhGH** [comment]
How weird, can you try turning off `cacheStartUrl`, setting `manifest.json.start_url` to `/test` then move `page.tsx` to `test/page.tsx` and see if the problem still occurs? I don't have an Android, so can't really reproduce as described.

**Comment by terencehf** [comment]
Yes, regrettably the issue persists. I'm unable to understand whether this is a next13 caching issue or a scope or start_url setting issue. Do you have any other config or app settings I could tweak to debug further?

**Comment by DuCanhGH** [comment]
@terencehf that seems to mean that this is not related to `dynamicStartUrl`/`cacheStartUrl`, can you share your `page.tsx`? Please remember to conceal sensitive information if you do, though.

**Comment by terencehf** [comment]
Sure, here's the generally redacted page.tsx for functional clarity and ease of reading:

import { cookies } from "next/headers";
import UserComponent from "./components/UserComponent";

export default async function Home() {
  const cookie = cookies();
  const userToken = cookie.get("cookie-name")?.value;

  const getUserInfo = async () => {
    const res = await fetch(`${process.env.NEXT_PUBLIC_URL}api/endpoint-to-get-information`, {
      method: "POST",
      body: JSON.stringify({
        community: "" as string,
        sentToken: userToken as string,
      }),
    });
    const data = await res.json();
    return data;
  };

  const userInfo: UserType = await getUserInfo();

  return (
    <main className="">
      {userInfo.id !== "" ? (
        <UserComponent userInfo={userInfo} token={userToken as string} />
      ) : (
        <div>
          // landing page information that is not dependent on fetch call
        </div>
      )}
    </main>
  );
}

**Comment by DuCanhGH** [comment]
@terencehf can you try logging token and `userInfo` to see if they match? Like, run `npm run start --hostname YOUR_PRIVATE_IP` then access the page on your Android device through `http://YOUR_PRIVATE_IP:3000` (the two devices should be in the same network). If there's no log when you first access the page then it's probably a caching issue on Next.js/`next-pwa`'s end, but otherwise I'd double check that API.

**Comment by terencehf** [comment]
Yes! There seems to be no token when the page first loads on mobile (android) and upon refreshing the page, the token does log.

When you say double check the API, are you referring to whether a request is being made at all or whether the code it is executing is somehow incorrect?

In your reproduction, you're getting the latest token when you test on an iOS device?


Apologies for the errant formatting before, have made the edit.

**Comment by DuCanhGH** [comment]
@terencehf well I think if such thing happens then the API may have been cached somehow (by `next-pwa` or `Cache-Control` perhaps).
How the page logs no token on first load yet logs a token on second load is really weird to be honest. This seems to mean that the server had to process the request, but there wasn't a token at that time for some reason.

> In your reproduction, you're getting the latest token when you test on an iOS device?

Yeah, that is the case for me.

**Comment by terencehf** [comment]
>(I assume you saw undefined, rather than nothing at  all)

Yes, undefined is what I saw. 

>This seems to mean that the server had to process the request, but there wasn't a token at that time for some reason.

While this is most probably true, there is a suspicously short load time which is what makes me feel like the page is, at times, being served from a cache and the logic isn't running at all. **I could most definitely be wrong about this, though.**

I do apologize, I'm a little out of my depth here. Is there something I can do, or somewhere I can look  to further debug this? I truly thank you for the time you've taken to look into this with me thus far.

**Comment by DuCanhGH** [comment]
> While this is most probably true, there is a suspicously short load time which is what makes me feel like the page is, at times, being served from a cache and the logic isn't running at all. I could most definitely be wrong about this, though.

Well if the page is served from cache then there shouldn't be no log at all. Or at least, a log with a token (we use NetworkOnly by default for pages, so the service worker will most likely reach the server to refresh the cache).

All this makes me feel like there's something wrong with the request itself. Maybe the page was requested with improper `Cookie` header on first load? Or perhaps something's wrong with `next-pwa`'s cache handling that rendered the request invalid? I, too, am out of my depths here unfortunately, but I will investigate tomorrow alongside with issue 79 (hopefully).

**Comment by terencehf** [comment]
I appreciate you looking into it whenever you get the time. Do let me know if I can be of any help!

**Comment by DuCanhGH** [comment]
@terencehf I looked around the repo to see if we were doing something weird with headers, but didn't manage to find any. Perhaps this is some weird problem related to the browser or Next.js' server because how the `Cookie` header seems to only be available in the second load is just really weird. Maybe you should try reproducing this without `next-pwa` (with `manifest.json` if needed)? Also try adding this:
```ts
// @ts-ignore
console.log([...headers().entries()], cookies().getAll());
```
then visit the page through that Android device again :)

**Comment by terencehf** [comment]
Sounds good. Will try and then update you on what I find!

**Comment by terencehf** [comment]
```
console.log("DuCanhGH's LOG: ", headers(), cookies().getAll());
result ^ DuCanhGH's LOG: HeadersList { cookies: null, [Symbol(headers map)]: Map(0) {}, [Symbol(headers map sorted)]: null } []

```

So, disabling pwa and then running with just a manifest, installing and then making a request generally confirms the non-existence of a token on page load.
I had also written a redirect function to redirect a user to another url if no token exists and the redirect function does run in the installed pwa and redirects the user.

**Comment by DuCanhGH** [comment]
@terencehf not gonna lie that's just weird, but this basically confirms that this is not related to `next-pwa` (assuming that you actually got rid of the service worker and Cache Storage). I'd suggest opening an issue in Next.js' repo at this point :)

**Comment by terencehf** [comment]
i did double check that the cache was removed and there was no sw. interestingly if I visit an authentication link sent via email that redirects me to a page within the app (not the '/' url) and sets a token, it does manage to register that a token is present when the eventual page loads, I can even navigate back to '/'  from there and everything works fine. However, if I close the pwa, kill it in the background and then reopen it, same issue of no token on initial '/' page load. Sigh. 

I should mark this issue closed here for now then, I guess. Will try and do some further debugging and see if I can find any way out of or around this. Thanks for all your help!

**Comment by DuCanhGH** [comment]
@terencehf hope you will be able to find the root cause soon :)
