### ISSUE TITLE
[Feature request]: Webm support for videos

### ISSUE THREAD

**Issue by katiasmet-93** [DuCanhGH/next-pwa#88]
### Which project is this feature idea for?

@ducanh2912/next-pwa

### Describe the feature you'd like to request

Is it possible to add webm support for video's? I tried to open a PR but I don't have permisson.

### Describe the solution you'd like

Add `webm` to the url pattern for videos.

### Describe alternatives you've considered

-

**Comment by DuCanhGH** [comment]
> Is it possible to add webm support for video's? I tried to open a PR but I don't have permisson.

I thought everyone can open a PR in my repo?

Also, you can add `workboxOptions.runtimeCaching` and `extendDefaultRuntimeCaching` to support webm files.

```js
const withPWA = require("@ducanh2912/next-pwa").default({
  extendDefaultRuntimeCaching: true,
  workboxOptions: {
    runtimeCaching: [
      {
        urlPattern: /\.(?:webm)$/i,
        handler: "CacheFirst",
        options: {
          rangeRequests: true,
          cacheName: "static-webm-assets",
          expiration: {
            maxEntries: 32,
            maxAgeSeconds: 24 * 60 * 60, // 24 hours
          },
        },
      },
    ],
  },
});

**Comment by katiasmet-93** [comment]
I couldn't push a feature branch to open as a PR :). 

I found that one out too! Thank you!!

**Comment by DuCanhGH** [comment]
@katiasmet-93 well you are supposed to fork the repo then create a PR from that fork back to my repo :)
