### ISSUE TITLE
[Docs]: Build of customer service worker

### ISSUE THREAD

**Issue by axelvaindal** [DuCanhGH/next-pwa#89]
### Provide environment information

Next 13.4.19 / next-pwa 9.6.0

### Whose documentation is this feedback for?

@ducanh2912/next-pwa

### Describe the problem

It appears custom service worker is not rebuilt on hot code change ?
Is that on purpose ?
Does this mean I have to restart my server everytime I change something in my custom service worker ?

### Expected behavior

I would expect my server to rebuild custom service worker on code change.

### Screenshots (if relevant)

<img width="1104" alt="image" src="https://github.com/DuCanhGH/next-pwa/assets/11026659/18a9c891-a008-4f35-8dff-89ad0cf6c4bd">

**Comment by DuCanhGH** [comment]
Should be fixed in `9.7.0` by setting `watchWorkersInDev` to `true` :)
