### ISSUE TITLE
How to implement `runtimeCaching`?

### ISSUE THREAD

**Issue by elsigh** [DuCanhGH/next-pwa#9]
Congratulations on this fork - it works for me Next 13 app dir while shadowwalker's was seemingly not working for me anymore

However I'm not sure what the best way to implement runtimeCaching (see https://github.com/shadowwalker/next-pwa/search?q=runtimeCaching) is now? I used to have this long config and then I'd seed my cache with a bunch of URLs manually (in addition to next/link doing so). 

What I'm trying to do is to set strategies for particul URL paths. For one of my paths I always want to be cache-first because I've loaded all the data I need to render any page into an IndexedDB database so I don't need to go to the network at all.

Currently I'm trying to do this in the code near where I'm calling wb.register() but I think I'm doing it wrong.

```
import { registerRoute } from "workbox-routing";
import { CacheFirst } from "workbox-strategies";
registerRoute(/.*\/song\/.*/, new CacheFirst({ cacheName: "others" }));
```

**Comment by elsigh** [comment]
ah, nm I realize you just embedded this inside of `workboxOptions` config key

**Comment by DuCanhGH** [comment]
@elsigh I'm glad you solved it - moving Workbox's options to a separate `workboxOptions` was one of my fork's first breaking changes, and it's the reason why my fork is at its 7.x right now :)

**Comment by elsigh** [comment]
@DuCanhGH I don't know if you might be up for it, but I'm not having great luck implementing my own `runtimeCaching` customization in `workboxOptions`. If you'd be up for a chat sometime that'd be amazing. I've been trying to get this configuration right for a couple of years now to no avail.

My app holds all of the relevant data it needs to render on the client in IndexedDB. So I want all possible URLs to effectively be CacheFirst when I'm offline.

Here's my site without any customization of runtimeCaching:
https://songbook-studio-mndgotl72-songbookstudio.vercel.app/
When offline:
- I can reload the home page / but if I click on any of the songs on the left navigation doesn't work.

with `runtimeCaching` (I copied cache.ts array and a few others an pasted into next.config.js)
https://songbook-studio-kodd589yz-songbookstudio.vercel.app/
When offline:
- homepage doesn't load

Any chance you'd be down to pair with me? Happy to help fund this project!

**Comment by DuCanhGH** [comment]
@elsigh I'm not really sure I can help, but using `PluginOptions.cacheOnFrontEndNav` does help by caching pages as you navigate so that they can be available offline next time you visit the website. Then you can copy `cache.ts` and change the handler for "others" to "CacheFirst". I haven't figured out why `next/link` doesn't work at all when offline, maybe that just is the difference between direct visits and client-transitions. I'll look into that this weekend if possible :)

**Comment by elsigh** [comment]
No worries! I did what you suggested and I basically get a behavior that I can't figure out.
If I load my site and navigate to a page then back to / and then go offline, I can navigate to that page just fine but .. if I refresh (which works) then try to click the link to that URL (which I can see is in the "others" cache) I get an application error/failure. Also the URLs are not updating when I navigate.
Ah the joy of ServiceWorker.

**Comment by DuCanhGH** [comment]
@elsigh it may be because prefetching failed :( I think I'll have to look for a way to make it work offline this weekend then.

**Comment by elsigh** [comment]
Yeah, you can experience what I'm referring to on https://songbook.studio/ - I know this is a hard problem! If you're particularly committed to making this work great with current Next.js (sure seems like it) let me know -  I would like to sponsor your project!

**Comment by elsigh** [comment]
btw @DuCanhGH  - are you ever on Discord or Slack? Would love to collab sometime.

**Comment by DuCanhGH** [comment]
@elsigh so I tried to implement the offline support. To summarize, I think it's really hard in the plugin's current state.

I'm having trouble fixing the offline support - I want to use another cache to cache Next's prefetch responses (which is of type `application/octet-stream`), let's say it's `others-flight-response` because if we send it a `text/html` response, Next will handle the link as if we are in an MPA. workbox's CacheableResponse (which I use to check `Content-Type`) seems to not check if the header's value is null and so cache the response of a normal page fetch (`text/html`) into the wrong cache (`others-flight-response` instead of `others`). So I tried to write my own version of CacheableResponse that checks if the header is defined and to my surprise, workbox just plain out refuses to compile because it found an unknown attribute on the class (`_cacheableResponse`). I tried to use a function instead:
```js
const CacheableResponsePlugin = (config) => {
    const cacheableResponse = new CacheableResponse(config);
    return {
        cacheWillUpdate: ({ response }) => {
            // reference cacheableResponse
        }
    }
}
```
workbox just kinda copies the return part, and so cacheableResponse is undefined in the SW. I think the offline support has to be put off for now, I will investigate again next weekend :( I may write a brand new package that doesn't use workbox though, as it kinda is dead anyway. That will also help me save some time when Turbopack gets released xD

**Comment by wyozi** [comment]
Hey @DuCanhGH. Thanks for work on the fork :)

What's the current status on offline mode? Testing the latest version of next-pwa locally, it seems like already-loaded pages mostly work in offline, but trying to refresh (press f5 in browser) breaks the page.

**Comment by DuCanhGH** [comment]
@wyozi that sounds like the `"Content-Type": "text/html"` of the page isn't cached but the `"Content-Type": "text/x-component"` one is. Can you try going online again, reload the page, then go offline and reload it once more? Thanks!

**Comment by wyozi** [comment]
@DuCanhGH Yeah, seems to work perfectly then! 

Adding `<link rel="prefetch" href="/the/other/path" />` to page <head> seems to correctly cache the `text/html` version as well. I don't know if there's a way to implement it automatically though.

**Comment by kylereblora** [comment]
Hi @DuCanhGH, based on the previous replies, it seems that the user would have to visit the page first online so they could navigate to it properly offline. I have a few questions:

1. Is there a way to sort of "precache" certain pages so they are available for offline use even though the user hasn't visited them yet? 
2. Does `cacheOnFrontendNav` only work on statically-generated pages?
3. If the user visits a server-rendered page online then goes offline, how long would it be "cached" for offline use?

Thanks!

**Comment by DuCanhGH** [comment]
@kylereblora here is my answers:
1. I'm not sure either, maybe `workbox.additionalManifestEntries` or a custom worker would help, but I don't know if you can precache RSC payloads that way.
2. `cacheOnFrontEndNav` doesn't know whether it is a statically generated page or not, so probably no.
3. These pages will be cached for 24 hours, though `next-pwa` (with its default options) uses `NetworkFirst` for pages so it will send a request to your server first if online.

**Comment by kylereblora** [comment]
Thanks @DuCanhGH. I wanted to clarify the behavior for `cacheOnFrontEndNav`. Am I correct in understanding that pages navigated by `next/link` will only be cached once the user had visited them?

**Comment by DuCanhGH** [comment]
@kylereblora `next-pwa` should cache a page's RSC payload when it is prefetched or visited (both through `next/link` and direct access) and its HTML when it is visited directly (and through `next/link` if `cacheOnFrontEndNav` is enabled).

**Comment by kylereblora** [comment]
Thanks @DuCanhGH! I'm quite interested in making certain pages available offline without letting the user visit them first. Will explore this for the meantime.

**Comment by baryosef-loops** [comment]
Hi, first thanks for all efforts to all contributors of this package!

I found this thread when was looking for a way to precache some specific HTML routes, so the app become fully accessible in offline after the first visit.

I refer to this code in `next-pwa/packages/next-pwa/src/index.ts`:

```ts

  let manifestEntries = additionalManifestEntries ?? [];

  if (!manifestEntries) {
    manifestEntries = fg
      .sync(
        [
          "**/*",
          "!workbox-*.js",
          "!workbox-*.js.map",
          "!worker-*.js",
          "!worker-*.js.map",
          "!fallback-*.js",
          "!fallback-*.js.map",
          `!${sw.replace(/^\/+/, "")}`,
          `!${sw.replace(/^\/+/, "")}.map`,
          ...publicExcludes,
        ],
        {
          cwd: "public",
        }
      )
      .map((f) => ({
        url: path.posix.join(basePath, f),
        revision: getFileHash(`public/${f}`),
      }));
  }

  if (cacheStartUrl) {
    if (!dynamicStartUrl) {
      manifestEntries.push({
        url: basePath,
        revision: buildId,
      });
    } else if (
      typeof dynamicStartUrlRedirect === "string" &&
      dynamicStartUrlRedirect.length > 0
    ) {
      manifestEntries.push({
        url: dynamicStartUrlRedirect,
        revision: buildId,
      });
    }
  }

+++  // my suggestion:
+++  if(extendDefaultPrecache){
+++    manifestEntries.push(extendDefaultPrecache.map( ({url, revision}) => {
+++     url,
+++     revision: revision !== undefined ? revision : buildId, // null is valid value
+++  });
+++
```

The `additionalManifestEntries` is not documented, but we can see here how it is used, it just fully override the default `manifestEntries` which represents all the static files created by next, right?

Will a simple change like my suggestion above work? Similar to `extendDefaultRuntimeCaching` but for this case. The `extendDefaultPrecache` may be an Array of assets to be added to `manifestEntries` instead replacing it completely? 

Is there any missing or hidden side effect that this change may introduce?
