### ISSUE TITLE
[Bug - next-pwa]: unknown field `lazy`, expected `resolveFully`

### ISSUE THREAD

**Issue by khuezy** [DuCanhGH/next-pwa#95]
### Provide environment information

Nextjs: 13.5.1
next-pwa: 9.7.0

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code help us address them faster

N/A

### To reproduce

When I have a custom worker file in `./worker/index.js`

```
self.__WB_DISABLE_DEV_LOGS = true

// listen to message event from window
self.addEventListener('message', event => {
  // HOW TO TEST THIS?
  // Run this in your browser console: 
  //     window.navigator.serviceWorker.controller.postMessage({command: 'log', message: 'hello world'})
  // OR use next-pwa injected workbox object
  //     window.workbox.messageSW({command: 'log', message: 'hello world'})
  console.log(event.data)
})
```

### Describe the bug

Running `npx dev`: 

```
./worker/index.js 39 bytes [built] [code generated] [1 error]

ERROR in ./worker/index.js
 Module build failed (from ../../node_modules/@ducanh2912/next-pwa/dist/swc-loader.cjs):
Error: unknown field `lazy`, expected `resolveFully` at line 1 column 440
```

The `worker-development.js` file contains:

```
/***/ "./worker/index.js":
/*!*************************!*\
  !*** ./worker/index.js ***!
  \*************************/
/***/ (() => {

eval("throw new Error(\"Module build failed (from ../../node_modules/@ducanh2912/next-pwa/dist/swc-loader.cjs):\\nError: unknown field `lazy`, expected `resolveFully` at line 1 column 440\");\n\n//# sourceURL=webpack://@myappnamespace/app/./worker/index.js?");

/***/ })

```

### Expected behavior

I'm not sure what I'm doing wrong, but I keep getting this error.

### Screenshots (if relevant)

N/a

### Additional information (if relevant)

N/a

**Comment by DuCanhGH** [comment]
This has got to be the third issue on this error...

**Comment by khuezy** [comment]
Thanks for the quick reply! Sorry, I didn't find a similar issue from the titles.

**Comment by khuezy** [comment]
Nvm I found it: https://github.com/DuCanhGH/next-pwa/issues/83

**Comment by DuCanhGH** [comment]
@khuezy yeah, you've got a point - those issues' titles make it really hard to know that they are about this error...

**Comment by joacub** [comment]
> @khuezy yeah, you've got a point - those issues' titles make it really hard to know that they are about this error...

yeah you are right, my badd im chaging now
